ggobiRandom <-
  #
  #
  #
function(fileName = character(0), dataMode = character(0), dim = c(70, 5))
{
  dim <- as.integer(dim)
  varNames <- letters[1:dim[2]]

  getVariableNames <- function() {
    varNames
  }

  getDims <- function() {
    cat("Getting dimension\n")
    print(dim)
    dim
  }

  getRecord <- function(which) {
     rnorm(dim[2])
  }

  getSourceDescription <- function(brief = TRUE) {
    ifelse(brief, "random", "Random data generated by R for GGobi using an input plugin")
  }
  
  getNumRecords <- function() {
    dim[1]
  }
  getNumVariables <- function() {
    dim[2]
  }  

  v <- list(
            getDims,
            getVariableNames,
            getRecord,            
            getSourceDescription,
            getNumRecords,
            getNumVariables            
            )
  
  class(v) <- c("Random", "GGobiInputPlugin")

  cat("Working on getting input from R\n")
  
  v
}


cat("Defined ggobiRandom\n")

