#!/bin/sh

rm -fr /usr/dfs/tmp/ggobi/*
cp *.c *.h Makefile local.config /usr/dfs/tmp/ggobi

mkdir /usr/dfs/tmp/ggobi/RS
cp RS/*.[chS] RS/GNUmakefile RS/README /usr/dfs/tmp/ggobi/RS

mkdir /usr/dfs/tmp/ggobi/RS/Src
cp RS/Src/*.S /usr/dfs/tmp/ggobi/RS/Src

mkdir /usr/dfs/tmp/ggobi/data
cp data/flea.* /usr/dfs/tmp/ggobi/data
cp data/ratcns.* /usr/dfs/tmp/ggobi/data

mkdir /usr/dfs/tmp/ggobi/notes
cp -r notes/* /usr/dfs/tmp/ggobi/notes
rm -rf /usr/dfs/tmp/ggobi/notes/CVS
rm -f /usr/dfs/tmp/ggobi/notes/*.aux

cd /usr/dfs/tmp
zip -r ggobi.zip ggobi
mv ggobi.zip /usr/dfs/xgobi/gtk

cd -
