ifndef GGOBI_HOME
 GGOBI_HOME=../..
endif

DIR_NAME=ggvis

include $(GGOBI_HOME)/plugins/GNUmakefile.PluginAdmin

createDist::
	if test ! -d $(INSTALL_DIR)/$(DIR_NAME); then mkdir $(INSTALL_DIR)/$(DIR_NAME)/R ; fi
	cp $(SRC:%=%.c) $(INSTALL_DIR)/$(DIR_NAME)
	cp $(HEADERS:%=%.h) $(INSTALL_DIR)/$(DIR_NAME)
	cp ggvis.h $(INSTALL_DIR)/$(DIR_NAME)
