#!/bin/sh

echo "$0, $1, $2, $3"

TARGET_DIR=$2

echo "Modifiying $2/bin/ggobi to point to $TARGET_DIR"
cat $2/bin/ggobi | sed -e "s|/usr/local/ggobi|${TARGET_DIR}|" > $2/TMP.ggobi
cat $2/TMP.ggobi

mv $2/TMP.ggobi $2/bin/ggobi
/bin/chmod a+x $2/bin/ggobi





