.TH ggobi 1 "30 September 2000"
.SH NAME
.B ggobi 
\- interactive dynamic graphics program for data visualization

.SH SYNOPSIS
.B ggobi
[
.B \-xml
]
filename

.SH DESCRIPTION
.I ggobi
is an interactive dynamic graphics program for data
visualization.  It is especially designed for the exploration of
multivariate data.  Its basic plot is a scatterplot, and these
are some of the tools available for scatterplot display and
manipulation:
.RS .25i
.IP o 2
Cycling rapidly through two-variable scatter plots.
.IP o 2
Grand tours and correlation tours: smooth randomized sequences of
two-dimensional projections in order to explore a higher-dimensional
point cloud of multivariate data. 
''' Projections can be manually
''' controlled and optimized with projection pursuit.
.IP o 2
Brushing: the ability to change the color or plotting
character of a point or a group of points.
.IP o 2
Hiding groups:  using checkboxes to specify which brushed
groups should be plotted, or included in calculations.
.IP o 2
Scaling: moving and reshaping the plot interactively.
.IP o 2
Identification: displaying a label next to a point in the plot window.
.IP o 2
Linked views: Brushing, identification and touring are linked;
that is, actions in one window are immediately reflected in
another window displaying the same data.
.IP o 2
Moving points:  Points can be moved on the screen.
''' In higher-dimensional views, the motion is interpreted as
''' taking place in some plane parallel to the screen.
.IP o 2
Subsetting: Subsamples can be drawn either systematically or randomly.
.IP o 2
Jittering: Variables can be jittered, which is useful for discrete
variables that take on only few values.
.IP o 2
Parallel coordinate display: a display of selected variables
using parallel (instead of orthogonal) axes.
.IP o 2
Scatterplot matrix display: 2-variable scatterplots
for selected variables.
.IP o 2
Missing values: are accepted and can be dealt with by imputation of
constant values, random values, or user-supplied imputed values.
Missing value patterns can be examined in a separate linked ggobi
window.
.IP o 2
Variable transformations: A menu of transformations 
is available.

''' .IP o 2
''' Smooths: Smooth curves can be drawn through point clouds.
''' .IP o 2
''' Case label list: shown in a separate window, linked to the main
''' window for labeling points.
''' .IP o 2
''' Postscript plotting: The contents of the plot windows can be written
''' out to postscript files for high-quality plotting.
''' .IP o 2
''' Line editing: Any pair of points can be connected with a line segment.
.RE

ggobi has a direct manipulation interface, and all the above actions
are performed using the mouse.

[Write something new here]
In addition, ggobi can be used in conjunction with the R or S
software for scientific computing and data analysis.  Execute
.IR help(ggobi)
within S or Splus for information; if the ggobi function
has not been installed, investigate the ggobi distribution files.

.SH OPTIONS

.B \-xml
.LP
.RS .25i
Use a single xml file as input instead of the set of files
used by xgobi (and still supported in ggobi).   The xml format
is documented in [].
.RE

.SH FILES
ggobi's file input can take two basic forms:  (1) the style
of multiple files, sharing a common basename, that was used
in xgobi, and (2) one file in xml.  A utility, xmlConvert,
is provided to transform a set of files into an xml file.

The multiple-file format is described here.  The data input file
should be an ASCII file with the data matrix arranged in rows and
columns; in ASCII, rows must be distinguished by carriage
returns, and columns can be separated by any amount of white
space.  Missing values can be coded as ".", "NA" or "na".  (The
input file can also be a binary file, which can be produced
within ggobi once the ASCII data has been read in.) ggobi accepts
other input about the display of the data from files as well.  If
the data is in a file named

.nf
.B filename
.fi

.RS .25i
or
.RE

.nf
.B filename.dat
.fi

.RS .25i
(either of which must be an ASCII file), or
.RE

.nf
.B filename.bin
.fi
.RS .25i

(the binary version of the data), then the other files are as follows:
.RE

.nf
.B filename.row
.B filename.rowlab
.B filename.case
.fi
.RS .25i

Row or case labels: a label for each row of the data matrix, which is
displayed in the identification mode.  The file should contain one
label per line.

.RE

.nf
.B filename.col
.B filename.collab
.B filename.column
.B filename.var
.fi
.RS .25i

Column or variable labels: a label for each column of the data matrix,
which becomes part of the ggobi variable selection panel.  The file
should contain one label per line. 

To add a short label to be used in the parallel coordinates plot, use
the vertical bar "|" as a field separator and add the short name, so
each line looks like this:  fullname|shortname.
.RE

.nf
.B filename.colors
.fi
.RS .25i

Brushing colors: a color for each point in the plot, representing a
row or case of the data.  The file should contain one color per line.
(It is probably best if the colors correspond to the colors used in
brushing; see the later section on resources.)
.RE

.nf
.B filename.glyphs
.fi
.RS .25i

Brushing glyphs: a glyph type for each point in the plot, representing
a row or case of the data.  The file should contain one glyph type per
line.  The glyph types are as follows:
.RS .25i

.nf
1 through 5: Five sizes of '+'
6 through 10: Five sizes of 'X'
11 through 15: Five sizes of open rectangle
16 through 20: Five sizes of filled rectangle
21 through 25: Five sizes of open circle
26 through 30: Five sizes of filled circle
31: A single-pixel point
.fi
.RE

.RE
.nf
.B filename.erase
.fi
.RS .25i

Erase: a column of 1s (to have a point hidden on startup) and 0s (to
have the point plotted).  There should be one value per line and as
many lines as there are rows in the data.
.RE

.nf
.B filename.lines
.fi
.RS .25i

Line segments: specifications for the pattern of line segments which
connect pairs of points.  The file should contain two numbers per
line.  The pair of numbers represents the row numbers of the two
points that should be connected.
.RE

.nf
.B filename.missing
.fi
.RS .25i

A file identical in structure to filename.dat, where non-zero values
indicate positions with missing (or censored, or otherwise
exceptional) values.  This file represents the pattern of missing
values in the data; it can be examined in a separate window by
selecting
.I New scatterplot 
or
.I New scatterplot matrix
from the
.I MISSING VALUES PLOTS
submenu of the
.I Window
menu.
.RE


.SH AUTHORS
.nf
Deborah Swayne (dfs@research.att.com)
Dianne Cook (dicook@iastate.edu)
Duncan Temple Lang (duncan@research.bell-labs.com)
Andreas Buja (andreas@research.att.com)
.fi
.SH CONTACT
Deborah Swayne (dfs@research.att.com)
.SH SEE ALSO
Sample data files are included in the ggobi distribution.

For papers and further pointers, check www.ggobi.org, and
the xgobi web site, www.research.att.com/areas/stat/xgobi.

.SH BUGS
Probably too numerous to mention, but you do the authors a favor if
you report the ones you notice.

