	"--activeColorScheme", "name of the default color scheme to use",
	"-activeColorScheme", "",
	"--colorschemes", "name of XML file containing color scheme descriptions.",
	"-colorschemes", "",
	"--datamode", "specify datamode (for plugins)",
	"-datamode", "",
	"--help", "display help on the console",
	"--home", "display GGobi home directory",
	"--init", "name of initialization file",
	"-keepalive", "don't terminate if no GGobi windows are open",
	"-mysql", "ignored. See --datamode.",
	"-noinit", "don't read any initialization files",
	"--plugin", "name of XML file for single plugin",
	"--restore", "restore a previously saved GGobi session.",
	"-restore", "",
	"-s", "use S (R or S-Plus) as the data mode",
	"--silent", "display little or no diagnostic output",
	"-silent", "",
	"-validate", "validate XML datasets during input",
	"-v", "",
	"--verbose", "display verbose diagnostic output on console",
	"-verbose", "",
	"-V", "",
	"--version", "display version information",
	"-version", "",
	"-xml", "use XML data format" \
