/* Generated by GOB (v2.0.18)   (do not edit directly) */

/* End world hunger, donate to the World Food Programme, http://www.wfp.org */

#define GOB_VERSION_MAJOR 2
#define GOB_VERSION_MINOR 0
#define GOB_VERSION_PATCHLEVEL 18

#define selfp (self->_priv)

#include <string.h> /* memset() */

#include "ggobi-renderer-factory.h"

#ifdef G_LIKELY
#define ___GOB_LIKELY(expr) G_LIKELY(expr)
#define ___GOB_UNLIKELY(expr) G_UNLIKELY(expr)
#else /* ! G_LIKELY */
#define ___GOB_LIKELY(expr) (expr)
#define ___GOB_UNLIKELY(expr) (expr)
#endif /* G_LIKELY */

#line 4 "renderer-factory.gob"

  #include <gtk/gtk.h>
  #if GTK_CHECK_VERSION(2,8,0)
  #include "ggobi-renderer-cairo.h"
  #else
  #define GGOBI_TYPE_RENDERER_CAIRO GGOBI_TYPE_RENDERER
  #endif

#line 33 "ggobi-renderer-factory.c"
/* self casting macros */
#define SELF(x) GGOBI_RENDERER_FACTORY(x)
#define SELF_CONST(x) GGOBI_RENDERER_FACTORY_CONST(x)
#define IS_SELF(x) GGOBI_IS_RENDERER_FACTORY(x)
#define TYPE_SELF GGOBI_TYPE_RENDERER_FACTORY
#define SELF_CLASS(x) GGOBI_RENDERER_FACTORY_CLASS(x)

#define SELF_GET_CLASS(x) GGOBI_RENDERER_FACTORY_GET_CLASS(x)

/* self typedefs */
typedef GGobiRendererFactory Self;
typedef GGobiRendererFactoryClass SelfClass;

/* here are local prototypes */
#line 1 "renderer-factory.gob"
static void ggobi_renderer_factory_init (GGobiRendererFactory * o) G_GNUC_UNUSED;
#line 50 "ggobi-renderer-factory.c"
#line 1 "renderer-factory.gob"
static void ggobi_renderer_factory_class_init (GGobiRendererFactoryClass * c) G_GNUC_UNUSED;
#line 53 "ggobi-renderer-factory.c"
static GGobiRenderer * ___real_ggobi_renderer_factory_create (GGobiRendererFactory * self, GdkDrawable * parent);

/* pointer to the class of our parent */
static GObjectClass *parent_class = NULL;

/* Short form macros */
#define self_new ggobi_renderer_factory_new
#define self_create ggobi_renderer_factory_create
GType
ggobi_renderer_factory_get_type (void)
{
	static GType type = 0;

	if ___GOB_UNLIKELY(type == 0) {
		static const GTypeInfo info = {
			sizeof (GGobiRendererFactoryClass),
			(GBaseInitFunc) NULL,
			(GBaseFinalizeFunc) NULL,
			(GClassInitFunc) ggobi_renderer_factory_class_init,
			(GClassFinalizeFunc) NULL,
			NULL /* class_data */,
			sizeof (GGobiRendererFactory),
			0 /* n_preallocs */,
			(GInstanceInitFunc) ggobi_renderer_factory_init,
			NULL
		};

		type = g_type_register_static (G_TYPE_OBJECT, "GGobiRendererFactory", &info, (GTypeFlags)0);
	}

	return type;
}

/* a macro for creating a new object of our type */
#define GET_NEW ((GGobiRendererFactory *)g_object_new(ggobi_renderer_factory_get_type(), NULL))

/* a function for creating a new object of our type */
#include <stdarg.h>
static GGobiRendererFactory * GET_NEW_VARG (const char *first, ...) G_GNUC_UNUSED;
static GGobiRendererFactory *
GET_NEW_VARG (const char *first, ...)
{
	GGobiRendererFactory *ret;
	va_list ap;
	va_start (ap, first);
	ret = (GGobiRendererFactory *)g_object_new_valist (ggobi_renderer_factory_get_type (), first, ap);
	va_end (ap);
	return ret;
}

static void 
ggobi_renderer_factory_init (GGobiRendererFactory * o G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "GGobi:Renderer:Factory::init"
}
#undef __GOB_FUNCTION__
static void 
ggobi_renderer_factory_class_init (GGobiRendererFactoryClass * c G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "GGobi:Renderer:Factory::class_init"

	parent_class = g_type_class_ref (G_TYPE_OBJECT);

#line 20 "renderer-factory.gob"
	c->create = ___real_ggobi_renderer_factory_create;
#line 119 "ggobi-renderer-factory.c"
}
#undef __GOB_FUNCTION__



#line 13 "renderer-factory.gob"
GGobiRendererFactory * 
ggobi_renderer_factory_new (void)
{
#line 129 "ggobi-renderer-factory.c"
#define __GOB_FUNCTION__ "GGobi:Renderer:Factory::new"
{
#line 15 "renderer-factory.gob"
	
    GObject *obj = (GObject *)GET_NEW;
    return GGOBI_RENDERER_FACTORY(obj);
  }}
#line 137 "ggobi-renderer-factory.c"
#undef __GOB_FUNCTION__

#line 20 "renderer-factory.gob"
GGobiRenderer * 
ggobi_renderer_factory_create (GGobiRendererFactory * self, GdkDrawable * parent)
{
#line 144 "ggobi-renderer-factory.c"
	GGobiRendererFactoryClass *klass;
#line 20 "renderer-factory.gob"
	g_return_val_if_fail (self != NULL, (GGobiRenderer * )0);
#line 20 "renderer-factory.gob"
	g_return_val_if_fail (GGOBI_IS_RENDERER_FACTORY (self), (GGobiRenderer * )0);
#line 150 "ggobi-renderer-factory.c"
	klass = GGOBI_RENDERER_FACTORY_GET_CLASS(self);

	if(klass->create)
		return (*klass->create)(self,parent);
	else
		return (GGobiRenderer * )(0);
}
#line 20 "renderer-factory.gob"
static GGobiRenderer * 
___real_ggobi_renderer_factory_create (GGobiRendererFactory * self G_GNUC_UNUSED, GdkDrawable * parent)
{
#line 162 "ggobi-renderer-factory.c"
#define __GOB_FUNCTION__ "GGobi:Renderer:Factory::create"
{
#line 22 "renderer-factory.gob"
	
    GObject *obj = g_object_new(GGOBI_TYPE_RENDERER, "parent", parent, NULL);
    return GGOBI_RENDERER(obj);
  }}
#line 170 "ggobi-renderer-factory.c"
#undef __GOB_FUNCTION__
