/* Generated by GOB (v2.0.18)   (do not edit directly) */

/* End world hunger, donate to the World Food Programme, http://www.wfp.org */

#define GOB_VERSION_MAJOR 2
#define GOB_VERSION_MINOR 0
#define GOB_VERSION_PATCHLEVEL 18

#define selfp (self->_priv)

#include <string.h> /* memset() */

#include "ggobi-renderer-cairo.h"

#ifdef G_LIKELY
#define ___GOB_LIKELY(expr) G_LIKELY(expr)
#define ___GOB_UNLIKELY(expr) G_UNLIKELY(expr)
#else /* ! G_LIKELY */
#define ___GOB_LIKELY(expr) (expr)
#define ___GOB_UNLIKELY(expr) (expr)
#endif /* G_LIKELY */

#line 1 "renderer-cairo.gob"
 /* only use cairo when GTK+ 2.8.0 or higher installed */
  #include <gtk/gtk.h>
  #if GTK_CHECK_VERSION(2,8,0)

#line 29 "ggobi-renderer-cairo.c"

#line 5 "renderer-cairo.gob"

  #include <math.h>
  /* Takes 1/64 degrees to radians and reverses */
  #define CAIRO_ANGLE(x) ((360 - (x/64.)) * M_PI / 180)
  /* millimeters per inch */
  #define MM_PER_INCH 25.4

#line 39 "ggobi-renderer-cairo.c"
/* self casting macros */
#define SELF(x) GGOBI_RENDERER_CAIRO(x)
#define SELF_CONST(x) GGOBI_RENDERER_CAIRO_CONST(x)
#define IS_SELF(x) GGOBI_IS_RENDERER_CAIRO(x)
#define TYPE_SELF GGOBI_TYPE_RENDERER_CAIRO
#define SELF_CLASS(x) GGOBI_RENDERER_CAIRO_CLASS(x)

#define SELF_GET_CLASS(x) GGOBI_RENDERER_CAIRO_GET_CLASS(x)

/* self typedefs */
typedef GGobiRendererCairo Self;
typedef GGobiRendererCairoClass SelfClass;

struct _GGobiRendererCairoPrivate {
#line 19 "renderer-cairo.gob"
	cairo_t * cairo;
#line 56 "ggobi-renderer-cairo.c"
};
/* here are local prototypes */
static void ___object_set_property (GObject *object, guint property_id, const GValue *value, GParamSpec *pspec);
static void ___object_get_property (GObject *object, guint property_id, GValue *value, GParamSpec *pspec);
#line 0 "renderer-cairo.gob"
static void ggobi_renderer_cairo_init (GGobiRendererCairo * o) G_GNUC_UNUSED;
#line 63 "ggobi-renderer-cairo.c"
#line 0 "renderer-cairo.gob"
static void ggobi_renderer_cairo_class_init (GGobiRendererCairoClass * c) G_GNUC_UNUSED;
#line 66 "ggobi-renderer-cairo.c"
#line 36 "renderer-cairo.gob"
static GdkDrawable * ___3_ggobi_renderer_cairo_create_target (GGobiRenderer * self, GdkDrawable * parent) G_GNUC_UNUSED;
#line 69 "ggobi-renderer-cairo.c"
static cairo_t * ___real_ggobi_renderer_cairo_create_cairo (GGobiRendererCairo * self, GdkDrawable * target);
#line 48 "renderer-cairo.gob"
static cairo_t * ggobi_renderer_cairo_create_cairo (GGobiRendererCairo * self, GdkDrawable * target) G_GNUC_UNUSED;
#line 73 "ggobi-renderer-cairo.c"
#line 54 "renderer-cairo.gob"
static void ggobi_renderer_cairo_line_type (GGobiRendererCairo * self, GdkGCValues * values) G_GNUC_UNUSED;
#line 76 "ggobi-renderer-cairo.c"
#line 103 "renderer-cairo.gob"
static void ggobi_renderer_cairo_stroke (GGobiRendererCairo * self, GdkGC * gc, gboolean filled) G_GNUC_UNUSED;
#line 79 "ggobi-renderer-cairo.c"
#line 118 "renderer-cairo.gob"
static void ggobi_renderer_cairo_polypath (GGobiRendererCairo * self, guint npoints, GdkPoint * points) G_GNUC_UNUSED;
#line 82 "ggobi-renderer-cairo.c"
#line 127 "renderer-cairo.gob"
static void ___8_ggobi_renderer_cairo_draw_rectangle (GdkDrawable * self, GdkGC * gc, gboolean filled, gint x, gint y, gint width, gint height) G_GNUC_UNUSED;
#line 85 "ggobi-renderer-cairo.c"
#line 135 "renderer-cairo.gob"
static void ___9_ggobi_renderer_cairo_draw_arc (GdkDrawable * self, GdkGC * gc, gboolean filled, gint x, gint y, gint width, gint height, gint angle1, gint angle2) G_GNUC_UNUSED;
#line 88 "ggobi-renderer-cairo.c"
#line 149 "renderer-cairo.gob"
static void ___a_ggobi_renderer_cairo_draw_polygon (GdkDrawable * self, GdkGC * gc, gboolean filled, GdkPoint * points, gint npoints) G_GNUC_UNUSED;
#line 91 "ggobi-renderer-cairo.c"
#line 158 "renderer-cairo.gob"
static void ___b_ggobi_renderer_cairo_draw_points (GdkDrawable * self, GdkGC * gc, GdkPoint * points, gint npoints) G_GNUC_UNUSED;
#line 94 "ggobi-renderer-cairo.c"
#line 168 "renderer-cairo.gob"
static void ___c_ggobi_renderer_cairo_draw_segments (GdkDrawable * self, GdkGC * gc, GdkSegment * segs, gint nsegs) G_GNUC_UNUSED;
#line 97 "ggobi-renderer-cairo.c"
#line 180 "renderer-cairo.gob"
static void ___d_ggobi_renderer_cairo_draw_lines (GdkDrawable * self, GdkGC * gc, GdkPoint * points, gint npoints) G_GNUC_UNUSED;
#line 100 "ggobi-renderer-cairo.c"
#line 186 "renderer-cairo.gob"
static void ___e_ggobi_renderer_cairo_draw_trapezoids (GdkDrawable * self, GdkGC * gc, GdkTrapezoid * trapezoids, gint n_trapezoids) G_GNUC_UNUSED;
#line 103 "ggobi-renderer-cairo.c"
#line 214 "renderer-cairo.gob"
static void ___11_ggobi_renderer_cairo_draw_glyphs (GdkDrawable * self, GdkGC * gc, PangoFont * font, gint x, gint y, PangoGlyphString * glyphs) G_GNUC_UNUSED;
#line 106 "ggobi-renderer-cairo.c"
#line 221 "renderer-cairo.gob"
static void ___12_ggobi_renderer_cairo_draw_glyphs_transformed (GdkDrawable * self, GdkGC * gc, PangoMatrix * matrix, PangoFont * font, gint x, gint y, PangoGlyphString * glyphs) G_GNUC_UNUSED;
#line 109 "ggobi-renderer-cairo.c"
#line 234 "renderer-cairo.gob"
static void ___13_ggobi_renderer_cairo_draw_drawable (GdkDrawable * self, GdkGC * gc, GdkDrawable * src, gint xsrc, gint ysrc, gint xdest, gint ydest, gint width, gint height) G_GNUC_UNUSED;
#line 112 "ggobi-renderer-cairo.c"
#line 248 "renderer-cairo.gob"
static GdkDrawable * ___14_ggobi_renderer_cairo_get_composite_drawable (GdkDrawable * self, gint x, gint y, gint width, gint height, gint * composite_x_offset, gint * composite_y_offset) G_GNUC_UNUSED;
#line 115 "ggobi-renderer-cairo.c"
#line 266 "renderer-cairo.gob"
static cairo_surface_t * ___15_ggobi_renderer_cairo_ref_cairo_surface (GdkDrawable * self) G_GNUC_UNUSED;
#line 118 "ggobi-renderer-cairo.c"

enum {
	PROP_0,
	PROP_CAIRO
};

/* pointer to the class of our parent */
static GGobiRendererClass *parent_class = NULL;

/* Short form macros */
#define self_get_cairo ggobi_renderer_cairo_get_cairo
#define self_set_cairo ggobi_renderer_cairo_set_cairo
#define self_create_cairo ggobi_renderer_cairo_create_cairo
#define self_line_type ggobi_renderer_cairo_line_type
#define self_stroke ggobi_renderer_cairo_stroke
#define self_polypath ggobi_renderer_cairo_polypath
GType
ggobi_renderer_cairo_get_type (void)
{
	static GType type = 0;

	if ___GOB_UNLIKELY(type == 0) {
		static const GTypeInfo info = {
			sizeof (GGobiRendererCairoClass),
			(GBaseInitFunc) NULL,
			(GBaseFinalizeFunc) NULL,
			(GClassInitFunc) ggobi_renderer_cairo_class_init,
			(GClassFinalizeFunc) NULL,
			NULL /* class_data */,
			sizeof (GGobiRendererCairo),
			0 /* n_preallocs */,
			(GInstanceInitFunc) ggobi_renderer_cairo_init,
			NULL
		};

		type = g_type_register_static (GGOBI_TYPE_RENDERER, "GGobiRendererCairo", &info, (GTypeFlags)0);
	}

	return type;
}

/* a macro for creating a new object of our type */
#define GET_NEW ((GGobiRendererCairo *)g_object_new(ggobi_renderer_cairo_get_type(), NULL))

/* a function for creating a new object of our type */
#include <stdarg.h>
static GGobiRendererCairo * GET_NEW_VARG (const char *first, ...) G_GNUC_UNUSED;
static GGobiRendererCairo *
GET_NEW_VARG (const char *first, ...)
{
	GGobiRendererCairo *ret;
	va_list ap;
	va_start (ap, first);
	ret = (GGobiRendererCairo *)g_object_new_valist (ggobi_renderer_cairo_get_type (), first, ap);
	va_end (ap);
	return ret;
}


static void
___finalize(GObject *obj_self)
{
#define __GOB_FUNCTION__ "GGobi:Renderer:Cairo::finalize"
	GGobiRendererCairo *self G_GNUC_UNUSED = GGOBI_RENDERER_CAIRO (obj_self);
	gpointer priv G_GNUC_UNUSED = self->_priv;
	if(G_OBJECT_CLASS(parent_class)->finalize) \
		(* G_OBJECT_CLASS(parent_class)->finalize)(obj_self);
#line 19 "renderer-cairo.gob"
	if(self->_priv->cairo) { cairo_destroy ((gpointer) self->_priv->cairo); self->_priv->cairo = NULL; }
#line 188 "ggobi-renderer-cairo.c"
}
#undef __GOB_FUNCTION__

static void 
ggobi_renderer_cairo_init (GGobiRendererCairo * o G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "GGobi:Renderer:Cairo::init"
	o->_priv = G_TYPE_INSTANCE_GET_PRIVATE(o,GGOBI_TYPE_RENDERER_CAIRO,GGobiRendererCairoPrivate);
}
#undef __GOB_FUNCTION__
static void 
ggobi_renderer_cairo_class_init (GGobiRendererCairoClass * c G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "GGobi:Renderer:Cairo::class_init"
	GObjectClass *g_object_class G_GNUC_UNUSED = (GObjectClass*) c;
	GGobiRendererClass *ggobi_renderer_class = (GGobiRendererClass *)c;
	GdkDrawableClass *gdk_drawable_class = (GdkDrawableClass *)c;

	g_type_class_add_private(c,sizeof(GGobiRendererCairoPrivate));

	parent_class = g_type_class_ref (GGOBI_TYPE_RENDERER);

#line 36 "renderer-cairo.gob"
	ggobi_renderer_class->create_target = ___3_ggobi_renderer_cairo_create_target;
#line 48 "renderer-cairo.gob"
	c->create_cairo = ___real_ggobi_renderer_cairo_create_cairo;
#line 127 "renderer-cairo.gob"
	gdk_drawable_class->draw_rectangle = ___8_ggobi_renderer_cairo_draw_rectangle;
#line 135 "renderer-cairo.gob"
	gdk_drawable_class->draw_arc = ___9_ggobi_renderer_cairo_draw_arc;
#line 149 "renderer-cairo.gob"
	gdk_drawable_class->draw_polygon = ___a_ggobi_renderer_cairo_draw_polygon;
#line 158 "renderer-cairo.gob"
	gdk_drawable_class->draw_points = ___b_ggobi_renderer_cairo_draw_points;
#line 168 "renderer-cairo.gob"
	gdk_drawable_class->draw_segments = ___c_ggobi_renderer_cairo_draw_segments;
#line 180 "renderer-cairo.gob"
	gdk_drawable_class->draw_lines = ___d_ggobi_renderer_cairo_draw_lines;
#line 186 "renderer-cairo.gob"
	gdk_drawable_class->draw_trapezoids = ___e_ggobi_renderer_cairo_draw_trapezoids;
#line 229 "ggobi-renderer-cairo.c"
	gdk_drawable_class->draw_text = NULL;
	gdk_drawable_class->draw_text_wc = NULL;
#line 214 "renderer-cairo.gob"
	gdk_drawable_class->draw_glyphs = ___11_ggobi_renderer_cairo_draw_glyphs;
#line 221 "renderer-cairo.gob"
	gdk_drawable_class->draw_glyphs_transformed = ___12_ggobi_renderer_cairo_draw_glyphs_transformed;
#line 234 "renderer-cairo.gob"
	gdk_drawable_class->draw_drawable = ___13_ggobi_renderer_cairo_draw_drawable;
#line 248 "renderer-cairo.gob"
	gdk_drawable_class->get_composite_drawable = ___14_ggobi_renderer_cairo_get_composite_drawable;
#line 266 "renderer-cairo.gob"
	gdk_drawable_class->ref_cairo_surface = ___15_ggobi_renderer_cairo_ref_cairo_surface;
#line 242 "ggobi-renderer-cairo.c"
	g_object_class->finalize = ___finalize;
	g_object_class->get_property = ___object_get_property;
	g_object_class->set_property = ___object_set_property;
    {
	GParamSpec   *param_spec;

	param_spec = g_param_spec_pointer
		("cairo" /* name */,
		 "cr" /* nick */,
		 "The cairo context to which this renders" /* blurb */,
		 (GParamFlags)(G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
	g_object_class_install_property (g_object_class,
		PROP_CAIRO,
		param_spec);
    }
}
#undef __GOB_FUNCTION__

static void
___object_set_property (GObject *object,
	guint property_id,
	const GValue *VAL G_GNUC_UNUSED,
	GParamSpec *pspec G_GNUC_UNUSED)
#define __GOB_FUNCTION__ "GGobi:Renderer:Cairo::set_property"
{
	GGobiRendererCairo *self G_GNUC_UNUSED;

	self = GGOBI_RENDERER_CAIRO (object);

	switch (property_id) {
	case PROP_CAIRO:
		{
#line 25 "renderer-cairo.gob"

     if (g_value_get_pointer(VAL)) {
       if (selfp->cairo)
         cairo_destroy(selfp->cairo);
       selfp->cairo = cairo_reference(g_value_get_pointer(VAL));
     }
   
#line 283 "ggobi-renderer-cairo.c"
		}
		break;
	default:
/* Apparently in g++ this is needed, glib is b0rk */
#ifndef __PRETTY_FUNCTION__
#  undef G_STRLOC
#  define G_STRLOC	__FILE__ ":" G_STRINGIFY (__LINE__)
#endif
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}
#undef __GOB_FUNCTION__

static void
___object_get_property (GObject *object,
	guint property_id,
	GValue *VAL G_GNUC_UNUSED,
	GParamSpec *pspec G_GNUC_UNUSED)
#define __GOB_FUNCTION__ "GGobi:Renderer:Cairo::get_property"
{
	GGobiRendererCairo *self G_GNUC_UNUSED;

	self = GGOBI_RENDERER_CAIRO (object);

	switch (property_id) {
	case PROP_CAIRO:
		{
#line 32 "renderer-cairo.gob"

     g_value_set_pointer(VAL, selfp->cairo);
   
#line 316 "ggobi-renderer-cairo.c"
		}
		break;
	default:
/* Apparently in g++ this is needed, glib is b0rk */
#ifndef __PRETTY_FUNCTION__
#  undef G_STRLOC
#  define G_STRLOC	__FILE__ ":" G_STRINGIFY (__LINE__)
#endif
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}
#undef __GOB_FUNCTION__



#line 32 "renderer-cairo.gob"
cairo_t * 
ggobi_renderer_cairo_get_cairo (GGobiRendererCairo * self)
{
#line 337 "ggobi-renderer-cairo.c"
#define __GOB_FUNCTION__ "GGobi:Renderer:Cairo::get_cairo"
{
#line 22 "renderer-cairo.gob"
		cairo_t* val; g_object_get (G_OBJECT (self), "cairo", &val, NULL); return val;
}}
#line 343 "ggobi-renderer-cairo.c"
#undef __GOB_FUNCTION__

#line 25 "renderer-cairo.gob"
void 
ggobi_renderer_cairo_set_cairo (GGobiRendererCairo * self, cairo_t * val)
{
#line 350 "ggobi-renderer-cairo.c"
#define __GOB_FUNCTION__ "GGobi:Renderer:Cairo::set_cairo"
{
#line 22 "renderer-cairo.gob"
		g_object_set (G_OBJECT (self), "cairo", val, NULL);
}}
#line 356 "ggobi-renderer-cairo.c"
#undef __GOB_FUNCTION__

#line 36 "renderer-cairo.gob"
static GdkDrawable * 
___3_ggobi_renderer_cairo_create_target (GGobiRenderer * self G_GNUC_UNUSED, GdkDrawable * parent)
#line 362 "ggobi-renderer-cairo.c"
#define PARENT_HANDLER(___self,___parent) \
	((GGOBI_RENDERER_CLASS(parent_class)->create_target)? \
		(* GGOBI_RENDERER_CLASS(parent_class)->create_target)(___self,___parent): \
		((GdkDrawable * )0))
{
#define __GOB_FUNCTION__ "GGobi:Renderer:Cairo::create_target"
{
#line 38 "renderer-cairo.gob"
	 // FIXME: eventually we don't want to use the parent's drawable at all
    // -- we should override everything with cairo
    GdkDrawable *target = PARENT_HANDLER(self, parent);
    /* if we do not have a cairo context yet, try for a glitz (pbuffer)
       surface, otherwise fallback to image surface */
    if (!SELF(self)->_priv->cairo)
      SELF(self)->_priv->cairo = self_create_cairo(SELF(self), target);
    return target;
  }}
#line 380 "ggobi-renderer-cairo.c"
#undef __GOB_FUNCTION__
#undef PARENT_HANDLER

#line 48 "renderer-cairo.gob"
static cairo_t * 
ggobi_renderer_cairo_create_cairo (GGobiRendererCairo * self, GdkDrawable * target)
{
#line 388 "ggobi-renderer-cairo.c"
	GGobiRendererCairoClass *klass;
#line 48 "renderer-cairo.gob"
	g_return_val_if_fail (self != NULL, (cairo_t * )0);
#line 48 "renderer-cairo.gob"
	g_return_val_if_fail (GGOBI_IS_RENDERER_CAIRO (self), (cairo_t * )0);
#line 394 "ggobi-renderer-cairo.c"
	klass = GGOBI_RENDERER_CAIRO_GET_CLASS(self);

	if(klass->create_cairo)
		return (*klass->create_cairo)(self,target);
	else
		return (cairo_t * )(0);
}
#line 48 "renderer-cairo.gob"
static cairo_t * 
___real_ggobi_renderer_cairo_create_cairo (GGobiRendererCairo * self G_GNUC_UNUSED, GdkDrawable * target)
{
#line 406 "ggobi-renderer-cairo.c"
#define __GOB_FUNCTION__ "GGobi:Renderer:Cairo::create_cairo"
{
#line 50 "renderer-cairo.gob"
	
    return gdk_cairo_create(target);
  }}
#line 413 "ggobi-renderer-cairo.c"
#undef __GOB_FUNCTION__

#line 54 "renderer-cairo.gob"
static void 
ggobi_renderer_cairo_line_type (GGobiRendererCairo * self, GdkGCValues * values)
{
#line 420 "ggobi-renderer-cairo.c"
#define __GOB_FUNCTION__ "GGobi:Renderer:Cairo::line_type"
#line 54 "renderer-cairo.gob"
	g_return_if_fail (self != NULL);
#line 54 "renderer-cairo.gob"
	g_return_if_fail (GGOBI_IS_RENDERER_CAIRO (self));
#line 426 "ggobi-renderer-cairo.c"
{
#line 56 "renderer-cairo.gob"
	
    cairo_line_cap_t cap = CAIRO_LINE_CAP_ROUND;
    cairo_line_join_t join = CAIRO_LINE_JOIN_ROUND;
    /*static double dashes[8];
    gint i;*/
    
    cairo_set_line_width(selfp->cairo, values->line_width+1);
    
    switch(values->cap_style) {
      case GDK_CAP_ROUND:
        cap = CAIRO_LINE_CAP_ROUND;
      break;
      case GDK_CAP_BUTT:
      case GDK_CAP_NOT_LAST:
        cap = CAIRO_LINE_CAP_BUTT;
      break;
      case GDK_CAP_PROJECTING:
        cap = CAIRO_LINE_CAP_SQUARE;
      break;
    }
    cairo_set_line_cap(selfp->cairo, cap);
    
    switch(values->join_style) {
      case GDK_JOIN_ROUND:
        join = CAIRO_LINE_JOIN_ROUND;
      break;
      case GDK_JOIN_MITER:
        join = CAIRO_LINE_JOIN_MITER;
        //cairo_set_miter_limit(selfp->cairo, gc->lmitre);
      break;
      case GDK_JOIN_BEVEL:
        join = CAIRO_LINE_JOIN_BEVEL;
      break;
    }
    cairo_set_line_join(selfp->cairo, join);
    // FIXME: Don't know how to get the dashes out of the GdkGC
    // Perhaps we could extend GdkGC
    /*
    for(i = 0; i < 8 && gc->lty & 15; i++) {
      dashes[i] = gc->lty & 15;
      gc->lty = gc->lty >> 4;
    }
  
    
    cairo_set_dash(cr, dashes, i, 0);*/
  }}
#line 475 "ggobi-renderer-cairo.c"
#undef __GOB_FUNCTION__

#line 103 "renderer-cairo.gob"
static void 
ggobi_renderer_cairo_stroke (GGobiRendererCairo * self, GdkGC * gc, gboolean filled)
{
#line 482 "ggobi-renderer-cairo.c"
#define __GOB_FUNCTION__ "GGobi:Renderer:Cairo::stroke"
#line 103 "renderer-cairo.gob"
	g_return_if_fail (self != NULL);
#line 103 "renderer-cairo.gob"
	g_return_if_fail (GGOBI_IS_RENDERER_CAIRO (self));
#line 488 "ggobi-renderer-cairo.c"
{
#line 105 "renderer-cairo.gob"
	
    GdkColor color;
    GdkGCValues values;
    GdkColormap *colors = gdk_gc_get_colormap(gc);
    gdk_gc_get_values(gc, &values);
    gdk_colormap_query_color(colors, values.foreground.pixel, &color);
    //g_debug("color: %d %d %d", color.red, color.green, color.blue);
    gdk_cairo_set_source_color(selfp->cairo, &color);
    if (filled)
      cairo_fill_preserve(selfp->cairo);
    self_line_type(self, &values);
    cairo_stroke(selfp->cairo);
  }}
#line 504 "ggobi-renderer-cairo.c"
#undef __GOB_FUNCTION__

#line 118 "renderer-cairo.gob"
static void 
ggobi_renderer_cairo_polypath (GGobiRendererCairo * self, guint npoints, GdkPoint * points)
{
#line 511 "ggobi-renderer-cairo.c"
#define __GOB_FUNCTION__ "GGobi:Renderer:Cairo::polypath"
#line 118 "renderer-cairo.gob"
	g_return_if_fail (self != NULL);
#line 118 "renderer-cairo.gob"
	g_return_if_fail (GGOBI_IS_RENDERER_CAIRO (self));
#line 517 "ggobi-renderer-cairo.c"
{
#line 120 "renderer-cairo.gob"
	
    gint i;
    cairo_move_to(selfp->cairo, points[0].x, points[0].y);
    for (i = 1; i < npoints; i++)
      cairo_line_to(selfp->cairo, points[i].x, points[i].y);
  }}
#line 526 "ggobi-renderer-cairo.c"
#undef __GOB_FUNCTION__

#line 127 "renderer-cairo.gob"
static void 
___8_ggobi_renderer_cairo_draw_rectangle (GdkDrawable * self G_GNUC_UNUSED, GdkGC * gc, gboolean filled, gint x, gint y, gint width, gint height)
#line 532 "ggobi-renderer-cairo.c"
#define PARENT_HANDLER(___self,___gc,___filled,___x,___y,___width,___height) \
	{ if(GDK_DRAWABLE_CLASS(parent_class)->draw_rectangle) \
		(* GDK_DRAWABLE_CLASS(parent_class)->draw_rectangle)(___self,___gc,___filled,___x,___y,___width,___height); }
{
#define __GOB_FUNCTION__ "GGobi:Renderer:Cairo::draw_rectangle"
{
#line 130 "renderer-cairo.gob"
	
    //g_debug("drawing rect: %d %d %d %d", x, y, width, height);
    cairo_rectangle(SELF(self)->_priv->cairo, x, y, width, height);
    self_stroke(SELF(self), gc, filled);
  }}
#line 545 "ggobi-renderer-cairo.c"
#undef __GOB_FUNCTION__
#undef PARENT_HANDLER

#line 135 "renderer-cairo.gob"
static void 
___9_ggobi_renderer_cairo_draw_arc (GdkDrawable * self G_GNUC_UNUSED, GdkGC * gc, gboolean filled, gint x, gint y, gint width, gint height, gint angle1, gint angle2)
#line 552 "ggobi-renderer-cairo.c"
#define PARENT_HANDLER(___self,___gc,___filled,___x,___y,___width,___height,___angle1,___angle2) \
	{ if(GDK_DRAWABLE_CLASS(parent_class)->draw_arc) \
		(* GDK_DRAWABLE_CLASS(parent_class)->draw_arc)(___self,___gc,___filled,___x,___y,___width,___height,___angle1,___angle2); }
{
#define __GOB_FUNCTION__ "GGobi:Renderer:Cairo::draw_arc"
{
#line 138 "renderer-cairo.gob"
	
    //cairo_move_to(cr, x+r, y);
    cairo_t *cr = SELF(self)->_priv->cairo;
    cairo_save(cr);
    cairo_translate (cr, x + width / 2., y + height / 2.);
    cairo_scale (cr, (width / 2.), (height / 2.));
    //g_debug("drawing arc from: %f to %f", CAIRO_ANGLE(angle2), CAIRO_ANGLE(angle1));
    cairo_arc_negative (cr, 0., 0., 1., CAIRO_ANGLE(angle1), CAIRO_ANGLE(angle2));
    self_stroke(SELF(self), gc, filled);
    cairo_restore(cr);
  }}
#line 571 "ggobi-renderer-cairo.c"
#undef __GOB_FUNCTION__
#undef PARENT_HANDLER

#line 149 "renderer-cairo.gob"
static void 
___a_ggobi_renderer_cairo_draw_polygon (GdkDrawable * self G_GNUC_UNUSED, GdkGC * gc, gboolean filled, GdkPoint * points, gint npoints)
#line 578 "ggobi-renderer-cairo.c"
#define PARENT_HANDLER(___self,___gc,___filled,___points,___npoints) \
	{ if(GDK_DRAWABLE_CLASS(parent_class)->draw_polygon) \
		(* GDK_DRAWABLE_CLASS(parent_class)->draw_polygon)(___self,___gc,___filled,___points,___npoints); }
{
#define __GOB_FUNCTION__ "GGobi:Renderer:Cairo::draw_polygon"
{
#line 152 "renderer-cairo.gob"
	
    //g_debug("POLYGON");
    self_polypath(SELF(self), npoints, points);
    cairo_close_path(SELF(self)->_priv->cairo);
    self_stroke(SELF(self), gc, filled);
  }}
#line 592 "ggobi-renderer-cairo.c"
#undef __GOB_FUNCTION__
#undef PARENT_HANDLER

#line 158 "renderer-cairo.gob"
static void 
___b_ggobi_renderer_cairo_draw_points (GdkDrawable * self G_GNUC_UNUSED, GdkGC * gc, GdkPoint * points, gint npoints)
#line 599 "ggobi-renderer-cairo.c"
#define PARENT_HANDLER(___self,___gc,___points,___npoints) \
	{ if(GDK_DRAWABLE_CLASS(parent_class)->draw_points) \
		(* GDK_DRAWABLE_CLASS(parent_class)->draw_points)(___self,___gc,___points,___npoints); }
{
#define __GOB_FUNCTION__ "GGobi:Renderer:Cairo::draw_points"
{
#line 160 "renderer-cairo.gob"
	
    guint i;
    //g_debug("POINTS");
    cairo_t *cr = SELF(self)->_priv->cairo;
    for (i = 0; i < npoints; i++)
      cairo_rectangle(cr, points[i].x - 0.5, points[i].y - 0.5, 1., 1.);
    self_stroke(SELF(self), gc, FALSE);
  }}
#line 615 "ggobi-renderer-cairo.c"
#undef __GOB_FUNCTION__
#undef PARENT_HANDLER

#line 168 "renderer-cairo.gob"
static void 
___c_ggobi_renderer_cairo_draw_segments (GdkDrawable * self G_GNUC_UNUSED, GdkGC * gc, GdkSegment * segs, gint nsegs)
#line 622 "ggobi-renderer-cairo.c"
#define PARENT_HANDLER(___self,___gc,___segs,___nsegs) \
	{ if(GDK_DRAWABLE_CLASS(parent_class)->draw_segments) \
		(* GDK_DRAWABLE_CLASS(parent_class)->draw_segments)(___self,___gc,___segs,___nsegs); }
{
#define __GOB_FUNCTION__ "GGobi:Renderer:Cairo::draw_segments"
{
#line 170 "renderer-cairo.gob"
	
    guint i;
    //g_debug("SEGMENTS");
    cairo_t *cr = SELF(self)->_priv->cairo;
    for (i = 0; i < nsegs; i++) {
      cairo_move_to(cr, segs[i].x1, segs[i].y1);
      cairo_line_to(cr, segs[i].x2, segs[i].y2);
    }
    self_stroke(SELF(self), gc, FALSE);
  }}
#line 640 "ggobi-renderer-cairo.c"
#undef __GOB_FUNCTION__
#undef PARENT_HANDLER

#line 180 "renderer-cairo.gob"
static void 
___d_ggobi_renderer_cairo_draw_lines (GdkDrawable * self G_GNUC_UNUSED, GdkGC * gc, GdkPoint * points, gint npoints)
#line 647 "ggobi-renderer-cairo.c"
#define PARENT_HANDLER(___self,___gc,___points,___npoints) \
	{ if(GDK_DRAWABLE_CLASS(parent_class)->draw_lines) \
		(* GDK_DRAWABLE_CLASS(parent_class)->draw_lines)(___self,___gc,___points,___npoints); }
{
#define __GOB_FUNCTION__ "GGobi:Renderer:Cairo::draw_lines"
{
#line 182 "renderer-cairo.gob"
	
    self_polypath(SELF(self), npoints, points);
    self_stroke(SELF(self), gc, FALSE);
  }}
#line 659 "ggobi-renderer-cairo.c"
#undef __GOB_FUNCTION__
#undef PARENT_HANDLER

#line 186 "renderer-cairo.gob"
static void 
___e_ggobi_renderer_cairo_draw_trapezoids (GdkDrawable * self G_GNUC_UNUSED, GdkGC * gc, GdkTrapezoid * trapezoids, gint n_trapezoids)
#line 666 "ggobi-renderer-cairo.c"
#define PARENT_HANDLER(___self,___gc,___trapezoids,___n_trapezoids) \
	{ if(GDK_DRAWABLE_CLASS(parent_class)->draw_trapezoids) \
		(* GDK_DRAWABLE_CLASS(parent_class)->draw_trapezoids)(___self,___gc,___trapezoids,___n_trapezoids); }
{
#define __GOB_FUNCTION__ "GGobi:Renderer:Cairo::draw_trapezoids"
{
#line 189 "renderer-cairo.gob"
	
    guint i;
    cairo_t *cr = SELF(self)->_priv->cairo;
    for (i = 0; i < n_trapezoids; i++) {
      cairo_move_to(cr, trapezoids[i].x11, trapezoids[i].y1);
      cairo_line_to(cr, trapezoids[i].x21, trapezoids[i].y1);
      cairo_line_to(cr, trapezoids[i].x22, trapezoids[i].y2);
      cairo_line_to(cr, trapezoids[i].x12, trapezoids[i].y2);
      cairo_line_to(cr, trapezoids[i].x11, trapezoids[i].y1);
    }
    self_stroke(SELF(self), gc, FALSE);
  }}
#line 686 "ggobi-renderer-cairo.c"
#undef __GOB_FUNCTION__
#undef PARENT_HANDLER



#line 214 "renderer-cairo.gob"
static void 
___11_ggobi_renderer_cairo_draw_glyphs (GdkDrawable * self G_GNUC_UNUSED, GdkGC * gc, PangoFont * font, gint x, gint y, PangoGlyphString * glyphs)
#line 695 "ggobi-renderer-cairo.c"
#define PARENT_HANDLER(___self,___gc,___font,___x,___y,___glyphs) \
	{ if(GDK_DRAWABLE_CLASS(parent_class)->draw_glyphs) \
		(* GDK_DRAWABLE_CLASS(parent_class)->draw_glyphs)(___self,___gc,___font,___x,___y,___glyphs); }
{
#define __GOB_FUNCTION__ "GGobi:Renderer:Cairo::draw_glyphs"
{
#line 217 "renderer-cairo.gob"
	
    cairo_move_to(SELF(self)->_priv->cairo, x, y);
    pango_cairo_show_glyph_string(SELF(self)->_priv->cairo, font, glyphs);
  }}
#line 707 "ggobi-renderer-cairo.c"
#undef __GOB_FUNCTION__
#undef PARENT_HANDLER

#line 221 "renderer-cairo.gob"
static void 
___12_ggobi_renderer_cairo_draw_glyphs_transformed (GdkDrawable * self G_GNUC_UNUSED, GdkGC * gc, PangoMatrix * matrix, PangoFont * font, gint x, gint y, PangoGlyphString * glyphs)
#line 714 "ggobi-renderer-cairo.c"
#define PARENT_HANDLER(___self,___gc,___matrix,___font,___x,___y,___glyphs) \
	{ if(GDK_DRAWABLE_CLASS(parent_class)->draw_glyphs_transformed) \
		(* GDK_DRAWABLE_CLASS(parent_class)->draw_glyphs_transformed)(___self,___gc,___matrix,___font,___x,___y,___glyphs); }
{
#define __GOB_FUNCTION__ "GGobi:Renderer:Cairo::draw_glyphs_transformed"
{
#line 224 "renderer-cairo.gob"
	
    cairo_t *cr = SELF(self)->_priv->cairo;
    cairo_matrix_t cr_matrix = 
    { matrix->xx, matrix->xy, matrix->yx, matrix->yy, matrix->x0, matrix->y0 };
    cairo_save(cr);
    cairo_set_matrix(cr, &cr_matrix);
    GDK_DRAWABLE_GET_CLASS(self)->draw_glyphs(self, gc, font, x, y, glyphs);
    cairo_restore(cr);
  }}
#line 731 "ggobi-renderer-cairo.c"
#undef __GOB_FUNCTION__
#undef PARENT_HANDLER

#line 234 "renderer-cairo.gob"
static void 
___13_ggobi_renderer_cairo_draw_drawable (GdkDrawable * self G_GNUC_UNUSED, GdkGC * gc, GdkDrawable * src, gint xsrc, gint ysrc, gint xdest, gint ydest, gint width, gint height)
#line 738 "ggobi-renderer-cairo.c"
#define PARENT_HANDLER(___self,___gc,___src,___xsrc,___ysrc,___xdest,___ydest,___width,___height) \
	{ if(GDK_DRAWABLE_CLASS(parent_class)->draw_drawable) \
		(* GDK_DRAWABLE_CLASS(parent_class)->draw_drawable)(___self,___gc,___src,___xsrc,___ysrc,___xdest,___ydest,___width,___height); }
{
#define __GOB_FUNCTION__ "GGobi:Renderer:Cairo::draw_drawable"
{
#line 237 "renderer-cairo.gob"
	
    cairo_t *cr = SELF(self)->_priv->cairo;
    cairo_surface_t *surf = GDK_DRAWABLE_GET_CLASS(src)->ref_cairo_surface(src);
    cairo_set_source_surface(cr, surf, xdest - xsrc, ydest - ysrc);
    cairo_save(cr);
    cairo_rectangle(cr, xdest, ydest, width, height);
    cairo_clip(cr);
    cairo_paint(cr);
    cairo_restore(cr);
  }}
#line 756 "ggobi-renderer-cairo.c"
#undef __GOB_FUNCTION__
#undef PARENT_HANDLER

#line 248 "renderer-cairo.gob"
static GdkDrawable * 
___14_ggobi_renderer_cairo_get_composite_drawable (GdkDrawable * self G_GNUC_UNUSED, gint x, gint y, gint width, gint height, gint * composite_x_offset, gint * composite_y_offset)
#line 763 "ggobi-renderer-cairo.c"
#define PARENT_HANDLER(___self,___x,___y,___width,___height,___composite_x_offset,___composite_y_offset) \
	((GDK_DRAWABLE_CLASS(parent_class)->get_composite_drawable)? \
		(* GDK_DRAWABLE_CLASS(parent_class)->get_composite_drawable)(___self,___x,___y,___width,___height,___composite_x_offset,___composite_y_offset): \
		((GdkDrawable * )0))
{
#define __GOB_FUNCTION__ "GGobi:Renderer:Cairo::get_composite_drawable"
{
#line 251 "renderer-cairo.gob"
	
    GdkDrawable *parent, *composite;
    cairo_t *cr;
    g_object_get(G_OBJECT(self), "parent", &parent, NULL);
    composite = gdk_pixmap_new(parent, width, height, -1);
    cr = gdk_cairo_create(composite);
    cairo_set_source_surface(cr, cairo_get_target(SELF(self)->_priv->cairo), 
      -1*x, -1*y);
    cairo_paint(cr);
    cairo_destroy(cr);
    *composite_x_offset = 0;
    *composite_y_offset = 0;
    return composite;
  }}
#line 786 "ggobi-renderer-cairo.c"
#undef __GOB_FUNCTION__
#undef PARENT_HANDLER

#line 266 "renderer-cairo.gob"
static cairo_surface_t * 
___15_ggobi_renderer_cairo_ref_cairo_surface (GdkDrawable * self G_GNUC_UNUSED)
#line 793 "ggobi-renderer-cairo.c"
#define PARENT_HANDLER(___self) \
	((GDK_DRAWABLE_CLASS(parent_class)->ref_cairo_surface)? \
		(* GDK_DRAWABLE_CLASS(parent_class)->ref_cairo_surface)(___self): \
		((cairo_surface_t * )0))
{
#define __GOB_FUNCTION__ "GGobi:Renderer:Cairo::ref_cairo_surface"
{
#line 268 "renderer-cairo.gob"
	
    return cairo_surface_reference(cairo_get_target(SELF(self)->_priv->cairo));
  }}
#line 805 "ggobi-renderer-cairo.c"
#undef __GOB_FUNCTION__
#undef PARENT_HANDLER

#line 272 "renderer-cairo.gob"

  #endif

#line 813 "ggobi-renderer-cairo.c"
