/* Generated by GOB (v2.0.18)   (do not edit directly) */

/* End world hunger, donate to the World Food Programme, http://www.wfp.org */

#define GOB_VERSION_MAJOR 2
#define GOB_VERSION_MINOR 0
#define GOB_VERSION_PATCHLEVEL 18

#define selfp (self->_priv)

#include <string.h> /* memset() */

#include "ggobi-renderer.h"

#ifdef G_LIKELY
#define ___GOB_LIKELY(expr) G_LIKELY(expr)
#define ___GOB_UNLIKELY(expr) G_UNLIKELY(expr)
#else /* ! G_LIKELY */
#define ___GOB_LIKELY(expr) (expr)
#define ___GOB_UNLIKELY(expr) (expr)
#endif /* G_LIKELY */

#line 5 "renderer.gob"

  #include <gtk/gtk.h>
  #if GTK_CHECK_VERSION(2,8,0)
  static cairo_surface_t *ref_cairo_surface(GdkDrawable *self);
  #endif

#line 31 "ggobi-renderer.c"
/* self casting macros */
#define SELF(x) GGOBI_RENDERER(x)
#define SELF_CONST(x) GGOBI_RENDERER_CONST(x)
#define IS_SELF(x) GGOBI_IS_RENDERER(x)
#define TYPE_SELF GGOBI_TYPE_RENDERER
#define SELF_CLASS(x) GGOBI_RENDERER_CLASS(x)

#define SELF_GET_CLASS(x) GGOBI_RENDERER_GET_CLASS(x)

/* self typedefs */
typedef GGobiRenderer Self;
typedef GGobiRendererClass SelfClass;

struct _GGobiRendererPrivate {
#line 20 "renderer.gob"
	GdkDrawable * buffer;
#line 23 "renderer.gob"
	GdkDrawable * parent;
#line 50 "ggobi-renderer.c"
};
/* here are local prototypes */
static void ___object_set_property (GObject *object, guint property_id, const GValue *value, GParamSpec *pspec);
static void ___object_get_property (GObject *object, guint property_id, GValue *value, GParamSpec *pspec);
#line 0 "renderer.gob"
static void ggobi_renderer_init (GGobiRenderer * o) G_GNUC_UNUSED;
#line 57 "ggobi-renderer.c"
static GdkDrawable * ___real_ggobi_renderer_create_target (GGobiRenderer * self, GdkDrawable * parent);
#line 41 "renderer.gob"
static GdkDrawable * ggobi_renderer_create_target (GGobiRenderer * self, GdkDrawable * parent) G_GNUC_UNUSED;
#line 61 "ggobi-renderer.c"
static GGobiRenderer * ___real_ggobi_renderer_buffer (GGobiRenderer * self);
static void ___real_ggobi_renderer_flush (GGobiRenderer * self, GdkGC * gc, gint xsrc, gint ysrc, gint xdest, gint ydest, gint width, gint height);
#line 67 "renderer.gob"
static void ___4_ggobi_renderer_draw_rectangle (GdkDrawable * self, GdkGC * gc, gboolean filled, gint x, gint y, gint width, gint height) G_GNUC_UNUSED;
#line 66 "ggobi-renderer.c"
#line 74 "renderer.gob"
static void ___5_ggobi_renderer_draw_arc (GdkDrawable * self, GdkGC * gc, gboolean filled, gint x, gint y, gint width, gint height, gint angle1, gint angle2) G_GNUC_UNUSED;
#line 69 "ggobi-renderer.c"
#line 81 "renderer.gob"
static void ___6_ggobi_renderer_draw_polygon (GdkDrawable * self, GdkGC * gc, gboolean filled, GdkPoint * points, gint npoints) G_GNUC_UNUSED;
#line 72 "ggobi-renderer.c"
#line 88 "renderer.gob"
static void ___7_ggobi_renderer_draw_points (GdkDrawable * self, GdkGC * gc, GdkPoint * points, gint npoints) G_GNUC_UNUSED;
#line 75 "ggobi-renderer.c"
#line 94 "renderer.gob"
static void ___8_ggobi_renderer_draw_segments (GdkDrawable * self, GdkGC * gc, GdkSegment * segs, gint nsegs) G_GNUC_UNUSED;
#line 78 "ggobi-renderer.c"
#line 100 "renderer.gob"
static void ___9_ggobi_renderer_draw_lines (GdkDrawable * self, GdkGC * gc, GdkPoint * points, gint npoints) G_GNUC_UNUSED;
#line 81 "ggobi-renderer.c"
#line 106 "renderer.gob"
static void ___a_ggobi_renderer_draw_trapezoids (GdkDrawable * self, GdkGC * gc, GdkTrapezoid * trapezoids, gint n_trapezoids) G_GNUC_UNUSED;
#line 84 "ggobi-renderer.c"
#line 114 "renderer.gob"
static void ___b_ggobi_renderer_draw_text (GdkDrawable * self, GdkFont * font, GdkGC * gc, gint x, gint y, const gchar * text, gint text_length) G_GNUC_UNUSED;
#line 87 "ggobi-renderer.c"
#line 121 "renderer.gob"
static void ___c_ggobi_renderer_draw_text_wc (GdkDrawable * self, GdkFont * font, GdkGC * gc, gint x, gint y, const GdkWChar * text, gint text_length) G_GNUC_UNUSED;
#line 90 "ggobi-renderer.c"
#line 128 "renderer.gob"
static void ___d_ggobi_renderer_draw_glyphs (GdkDrawable * self, GdkGC * gc, PangoFont * font, gint x, gint y, PangoGlyphString * glyphs) G_GNUC_UNUSED;
#line 93 "ggobi-renderer.c"
#line 135 "renderer.gob"
static void ___e_ggobi_renderer_draw_glyphs_transformed (GdkDrawable * self, GdkGC * gc, PangoMatrix * matrix, PangoFont * font, gint x, gint y, PangoGlyphString * glyphs) G_GNUC_UNUSED;
#line 96 "ggobi-renderer.c"
#line 143 "renderer.gob"
static GdkGC * ___f_ggobi_renderer_create_gc (GdkDrawable * self, GdkGCValues * values, GdkGCValuesMask mask) G_GNUC_UNUSED;
#line 99 "ggobi-renderer.c"
#line 149 "renderer.gob"
static void ___10_ggobi_renderer_draw_drawable (GdkDrawable * self, GdkGC * gc, GdkDrawable * src, gint xsrc, gint ysrc, gint xdest, gint ydest, gint width, gint height) G_GNUC_UNUSED;
#line 102 "ggobi-renderer.c"
#line 156 "renderer.gob"
static void ___11_ggobi_renderer_draw_image (GdkDrawable * self, GdkGC * gc, GdkImage * image, gint xsrc, gint ysrc, gint xdest, gint ydest, gint width, gint height) G_GNUC_UNUSED;
#line 105 "ggobi-renderer.c"
#line 164 "renderer.gob"
static gint ___12_ggobi_renderer_get_depth (GdkDrawable * self) G_GNUC_UNUSED;
#line 108 "ggobi-renderer.c"
#line 170 "renderer.gob"
static void ___13_ggobi_renderer_get_size (GdkDrawable * self, gint * width, gint * height) G_GNUC_UNUSED;
#line 111 "ggobi-renderer.c"
#line 177 "renderer.gob"
static void ___14_ggobi_renderer_set_colormap (GdkDrawable * self, GdkColormap * cmap) G_GNUC_UNUSED;
#line 114 "ggobi-renderer.c"
#line 183 "renderer.gob"
static GdkColormap * ___15_ggobi_renderer_get_colormap (GdkDrawable * self) G_GNUC_UNUSED;
#line 117 "ggobi-renderer.c"
#line 189 "renderer.gob"
static GdkVisual * ___16_ggobi_renderer_get_visual (GdkDrawable * self) G_GNUC_UNUSED;
#line 120 "ggobi-renderer.c"
#line 195 "renderer.gob"
static GdkScreen * ___17_ggobi_renderer_get_screen (GdkDrawable * self) G_GNUC_UNUSED;
#line 123 "ggobi-renderer.c"
#line 201 "renderer.gob"
static GdkImage * ___18_ggobi_renderer_get_image (GdkDrawable * self, gint x, gint y, gint width, gint height) G_GNUC_UNUSED;
#line 126 "ggobi-renderer.c"
#line 207 "renderer.gob"
static GdkRegion * ___19_ggobi_renderer_get_clip_region (GdkDrawable * self) G_GNUC_UNUSED;
#line 129 "ggobi-renderer.c"
#line 213 "renderer.gob"
static GdkRegion * ___1a_ggobi_renderer_get_visible_region (GdkDrawable * self) G_GNUC_UNUSED;
#line 132 "ggobi-renderer.c"
#line 219 "renderer.gob"
static GdkDrawable * ___1b_ggobi_renderer_get_composite_drawable (GdkDrawable * self, gint x, gint y, gint width, gint height, gint * composite_x_offset, gint * composite_y_offset) G_GNUC_UNUSED;
#line 135 "ggobi-renderer.c"
#line 227 "renderer.gob"
static void ___1c_ggobi_renderer_draw_pixbuf (GdkDrawable * self, GdkGC * gc, GdkPixbuf * pixbuf, gint src_x, gint src_y, gint dest_x, gint dest_y, gint width, gint height, GdkRgbDither dither, gint x_dither, gint y_dither) G_GNUC_UNUSED;
#line 138 "ggobi-renderer.c"
#line 236 "renderer.gob"
static GdkImage * ___1d_ggobi_renderer__copy_to_image (GdkDrawable * self, GdkImage * image, gint src_x, gint src_y, gint dest_x, gint dest_y, gint width, gint height) G_GNUC_UNUSED;
#line 141 "ggobi-renderer.c"
#line 244 "renderer.gob"
static void ggobi_renderer_class_init (GGobiRendererClass * self_class) G_GNUC_UNUSED;
#line 144 "ggobi-renderer.c"

enum {
	PROP_0,
	PROP_PARENT
};

/* pointer to the class of our parent */
static GdkDrawableClass *parent_class = NULL;

/* Short form macros */
#define self_create_target ggobi_renderer_create_target
#define self_buffer ggobi_renderer_buffer
#define self_flush ggobi_renderer_flush
GType
ggobi_renderer_get_type (void)
{
	static GType type = 0;

	if ___GOB_UNLIKELY(type == 0) {
		static const GTypeInfo info = {
			sizeof (GGobiRendererClass),
			(GBaseInitFunc) NULL,
			(GBaseFinalizeFunc) NULL,
			(GClassInitFunc) ggobi_renderer_class_init,
			(GClassFinalizeFunc) NULL,
			NULL /* class_data */,
			sizeof (GGobiRenderer),
			0 /* n_preallocs */,
			(GInstanceInitFunc) ggobi_renderer_init,
			NULL
		};

		type = g_type_register_static (GDK_TYPE_DRAWABLE, "GGobiRenderer", &info, (GTypeFlags)0);
	}

	return type;
}

/* a macro for creating a new object of our type */
#define GET_NEW ((GGobiRenderer *)g_object_new(ggobi_renderer_get_type(), NULL))

/* a function for creating a new object of our type */
#include <stdarg.h>
static GGobiRenderer * GET_NEW_VARG (const char *first, ...) G_GNUC_UNUSED;
static GGobiRenderer *
GET_NEW_VARG (const char *first, ...)
{
	GGobiRenderer *ret;
	va_list ap;
	va_start (ap, first);
	ret = (GGobiRenderer *)g_object_new_valist (ggobi_renderer_get_type (), first, ap);
	va_end (ap);
	return ret;
}


static void
___dispose (GObject *obj_self)
{
#define __GOB_FUNCTION__ "GGobi:Renderer::dispose"
	GGobiRenderer *self G_GNUC_UNUSED = GGOBI_RENDERER (obj_self);
	if (G_OBJECT_CLASS (parent_class)->dispose) \
		(* G_OBJECT_CLASS (parent_class)->dispose) (obj_self);
#line 20 "renderer.gob"
	if(self->_priv->buffer) { g_object_unref ((gpointer) self->_priv->buffer); self->_priv->buffer = NULL; }
#line 210 "ggobi-renderer.c"
#line 23 "renderer.gob"
	if(self->_priv->parent) { g_object_unref ((gpointer) self->_priv->parent); self->_priv->parent = NULL; }
#line 213 "ggobi-renderer.c"
}
#undef __GOB_FUNCTION__


static void
___finalize(GObject *obj_self)
{
#define __GOB_FUNCTION__ "GGobi:Renderer::finalize"
	GGobiRenderer *self G_GNUC_UNUSED = GGOBI_RENDERER (obj_self);
	gpointer priv G_GNUC_UNUSED = self->_priv;
	if(G_OBJECT_CLASS(parent_class)->finalize) \
		(* G_OBJECT_CLASS(parent_class)->finalize)(obj_self);
}
#undef __GOB_FUNCTION__

static void 
ggobi_renderer_init (GGobiRenderer * o G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "GGobi:Renderer::init"
	o->_priv = G_TYPE_INSTANCE_GET_PRIVATE(o,GGOBI_TYPE_RENDERER,GGobiRendererPrivate);
}
#undef __GOB_FUNCTION__
#line 244 "renderer.gob"
static void 
ggobi_renderer_class_init (GGobiRendererClass * self_class G_GNUC_UNUSED)
{
#line 240 "ggobi-renderer.c"
#define __GOB_FUNCTION__ "GGobi:Renderer::class_init"
	GObjectClass *g_object_class G_GNUC_UNUSED = (GObjectClass*) self_class;
	GdkDrawableClass *gdk_drawable_class = (GdkDrawableClass *)self_class;

	g_type_class_add_private(self_class,sizeof(GGobiRendererPrivate));

	parent_class = g_type_class_ref (GDK_TYPE_DRAWABLE);

#line 41 "renderer.gob"
	self_class->create_target = ___real_ggobi_renderer_create_target;
#line 50 "renderer.gob"
	self_class->buffer = ___real_ggobi_renderer_buffer;
#line 57 "renderer.gob"
	self_class->flush = ___real_ggobi_renderer_flush;
#line 67 "renderer.gob"
	gdk_drawable_class->draw_rectangle = ___4_ggobi_renderer_draw_rectangle;
#line 74 "renderer.gob"
	gdk_drawable_class->draw_arc = ___5_ggobi_renderer_draw_arc;
#line 81 "renderer.gob"
	gdk_drawable_class->draw_polygon = ___6_ggobi_renderer_draw_polygon;
#line 88 "renderer.gob"
	gdk_drawable_class->draw_points = ___7_ggobi_renderer_draw_points;
#line 94 "renderer.gob"
	gdk_drawable_class->draw_segments = ___8_ggobi_renderer_draw_segments;
#line 100 "renderer.gob"
	gdk_drawable_class->draw_lines = ___9_ggobi_renderer_draw_lines;
#line 106 "renderer.gob"
	gdk_drawable_class->draw_trapezoids = ___a_ggobi_renderer_draw_trapezoids;
#line 114 "renderer.gob"
	gdk_drawable_class->draw_text = ___b_ggobi_renderer_draw_text;
#line 121 "renderer.gob"
	gdk_drawable_class->draw_text_wc = ___c_ggobi_renderer_draw_text_wc;
#line 128 "renderer.gob"
	gdk_drawable_class->draw_glyphs = ___d_ggobi_renderer_draw_glyphs;
#line 135 "renderer.gob"
	gdk_drawable_class->draw_glyphs_transformed = ___e_ggobi_renderer_draw_glyphs_transformed;
#line 143 "renderer.gob"
	gdk_drawable_class->create_gc = ___f_ggobi_renderer_create_gc;
#line 149 "renderer.gob"
	gdk_drawable_class->draw_drawable = ___10_ggobi_renderer_draw_drawable;
#line 156 "renderer.gob"
	gdk_drawable_class->draw_image = ___11_ggobi_renderer_draw_image;
#line 164 "renderer.gob"
	gdk_drawable_class->get_depth = ___12_ggobi_renderer_get_depth;
#line 170 "renderer.gob"
	gdk_drawable_class->get_size = ___13_ggobi_renderer_get_size;
#line 177 "renderer.gob"
	gdk_drawable_class->set_colormap = ___14_ggobi_renderer_set_colormap;
#line 183 "renderer.gob"
	gdk_drawable_class->get_colormap = ___15_ggobi_renderer_get_colormap;
#line 189 "renderer.gob"
	gdk_drawable_class->get_visual = ___16_ggobi_renderer_get_visual;
#line 195 "renderer.gob"
	gdk_drawable_class->get_screen = ___17_ggobi_renderer_get_screen;
#line 201 "renderer.gob"
	gdk_drawable_class->get_image = ___18_ggobi_renderer_get_image;
#line 207 "renderer.gob"
	gdk_drawable_class->get_clip_region = ___19_ggobi_renderer_get_clip_region;
#line 213 "renderer.gob"
	gdk_drawable_class->get_visible_region = ___1a_ggobi_renderer_get_visible_region;
#line 219 "renderer.gob"
	gdk_drawable_class->get_composite_drawable = ___1b_ggobi_renderer_get_composite_drawable;
#line 227 "renderer.gob"
	gdk_drawable_class->draw_pixbuf = ___1c_ggobi_renderer_draw_pixbuf;
#line 236 "renderer.gob"
	gdk_drawable_class->_copy_to_image = ___1d_ggobi_renderer__copy_to_image;
#line 307 "ggobi-renderer.c"
	g_object_class->dispose = ___dispose;
	g_object_class->finalize = ___finalize;
	g_object_class->get_property = ___object_get_property;
	g_object_class->set_property = ___object_set_property;
    {
	GParamSpec   *param_spec;

	param_spec = g_param_spec_object
		("parent" /* name */,
		 "out" /* nick */,
		 "The drawable to which this renderer is flushed" /* blurb */,
		 GDK_TYPE_DRAWABLE /* object_type */,
		 (GParamFlags)(G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
	g_object_class_install_property (g_object_class,
		PROP_PARENT,
		param_spec);
    }
 {
#line 244 "renderer.gob"
 /* need to do this one manually, to avoid GTK+ 2.8.x dep */
    #if GTK_CHECK_VERSION(2,8,0)
    GDK_DRAWABLE_CLASS(self_class)->ref_cairo_surface = ref_cairo_surface;
    #endif
  
#line 332 "ggobi-renderer.c"
 }
}
#undef __GOB_FUNCTION__

static void
___object_set_property (GObject *object,
	guint property_id,
	const GValue *VAL G_GNUC_UNUSED,
	GParamSpec *pspec G_GNUC_UNUSED)
#define __GOB_FUNCTION__ "GGobi:Renderer::set_property"
{
	GGobiRenderer *self G_GNUC_UNUSED;

	self = GGOBI_RENDERER (object);

	switch (property_id) {
	case PROP_PARENT:
		{
#line 27 "renderer.gob"

     GObject *obj = g_value_dup_object(VAL);
     if (selfp->parent)
       g_object_unref(G_OBJECT(selfp->parent));
     selfp->parent = GDK_DRAWABLE(obj);
     if (selfp->buffer)
       g_object_unref(G_OBJECT(selfp->buffer));
     selfp->buffer = self_create_target(self, selfp->parent);
   
#line 361 "ggobi-renderer.c"
		}
		break;
	default:
/* Apparently in g++ this is needed, glib is b0rk */
#ifndef __PRETTY_FUNCTION__
#  undef G_STRLOC
#  define G_STRLOC	__FILE__ ":" G_STRINGIFY (__LINE__)
#endif
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}
#undef __GOB_FUNCTION__

static void
___object_get_property (GObject *object,
	guint property_id,
	GValue *VAL G_GNUC_UNUSED,
	GParamSpec *pspec G_GNUC_UNUSED)
#define __GOB_FUNCTION__ "GGobi:Renderer::get_property"
{
	GGobiRenderer *self G_GNUC_UNUSED;

	self = GGOBI_RENDERER (object);

	switch (property_id) {
	case PROP_PARENT:
		{
#line 35 "renderer.gob"

     g_value_set_object(VAL, selfp->parent);
   
#line 394 "ggobi-renderer.c"
		}
		break;
	default:
/* Apparently in g++ this is needed, glib is b0rk */
#ifndef __PRETTY_FUNCTION__
#  undef G_STRLOC
#  define G_STRLOC	__FILE__ ":" G_STRINGIFY (__LINE__)
#endif
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}
#undef __GOB_FUNCTION__


#line 41 "renderer.gob"
static GdkDrawable * 
ggobi_renderer_create_target (GGobiRenderer * self, GdkDrawable * parent)
{
#line 414 "ggobi-renderer.c"
	GGobiRendererClass *klass;
#line 41 "renderer.gob"
	g_return_val_if_fail (self != NULL, (GdkDrawable * )0);
#line 41 "renderer.gob"
	g_return_val_if_fail (GGOBI_IS_RENDERER (self), (GdkDrawable * )0);
#line 420 "ggobi-renderer.c"
	klass = GGOBI_RENDERER_GET_CLASS(self);

	if(klass->create_target)
		return (*klass->create_target)(self,parent);
	else
		return (GdkDrawable * )(0);
}
#line 41 "renderer.gob"
static GdkDrawable * 
___real_ggobi_renderer_create_target (GGobiRenderer * self G_GNUC_UNUSED, GdkDrawable * parent)
{
#line 432 "ggobi-renderer.c"
#define __GOB_FUNCTION__ "GGobi:Renderer::create_target"
{
#line 43 "renderer.gob"
	
    gint width, height;
    gdk_drawable_get_size(parent, &width, &height);
    return gdk_pixmap_new(parent, width, height, -1);
  }}
#line 441 "ggobi-renderer.c"
#undef __GOB_FUNCTION__

#line 50 "renderer.gob"
GGobiRenderer * 
ggobi_renderer_buffer (GGobiRenderer * self)
{
#line 448 "ggobi-renderer.c"
	GGobiRendererClass *klass;
#line 50 "renderer.gob"
	g_return_val_if_fail (self != NULL, (GGobiRenderer * )0);
#line 50 "renderer.gob"
	g_return_val_if_fail (GGOBI_IS_RENDERER (self), (GGobiRenderer * )0);
#line 454 "ggobi-renderer.c"
	klass = GGOBI_RENDERER_GET_CLASS(self);

	if(klass->buffer)
		return (*klass->buffer)(self);
	else
		return (GGobiRenderer * )(0);
}
#line 50 "renderer.gob"
static GGobiRenderer * 
___real_ggobi_renderer_buffer (GGobiRenderer * self G_GNUC_UNUSED)
{
#line 466 "ggobi-renderer.c"
#define __GOB_FUNCTION__ "GGobi:Renderer::buffer"
{
#line 52 "renderer.gob"
	
    GObject *obj = g_object_new(G_OBJECT_TYPE(self), "parent", self, NULL);
    return GGOBI_RENDERER(obj);
  }}
#line 474 "ggobi-renderer.c"
#undef __GOB_FUNCTION__

#line 57 "renderer.gob"
void 
ggobi_renderer_flush (GGobiRenderer * self, GdkGC * gc, gint xsrc, gint ysrc, gint xdest, gint ydest, gint width, gint height)
{
#line 481 "ggobi-renderer.c"
	GGobiRendererClass *klass;
#line 57 "renderer.gob"
	g_return_if_fail (self != NULL);
#line 57 "renderer.gob"
	g_return_if_fail (GGOBI_IS_RENDERER (self));
#line 487 "ggobi-renderer.c"
	klass = GGOBI_RENDERER_GET_CLASS(self);

	if(klass->flush)
		(*klass->flush)(self,gc,xsrc,ysrc,xdest,ydest,width,height);
}
#line 57 "renderer.gob"
static void 
___real_ggobi_renderer_flush (GGobiRenderer * self G_GNUC_UNUSED, GdkGC * gc, gint xsrc, gint ysrc, gint xdest, gint ydest, gint width, gint height)
{
#line 497 "ggobi-renderer.c"
#define __GOB_FUNCTION__ "GGobi:Renderer::flush"
{
#line 60 "renderer.gob"
	
    gdk_draw_drawable(selfp->parent, gc, selfp->buffer, xsrc, ysrc, xdest, ydest, 
      width, height);
  }}
#line 505 "ggobi-renderer.c"
#undef __GOB_FUNCTION__

#line 67 "renderer.gob"
static void 
___4_ggobi_renderer_draw_rectangle (GdkDrawable * self G_GNUC_UNUSED, GdkGC * gc, gboolean filled, gint x, gint y, gint width, gint height)
#line 511 "ggobi-renderer.c"
#define PARENT_HANDLER(___self,___gc,___filled,___x,___y,___width,___height) \
	{ if(GDK_DRAWABLE_CLASS(parent_class)->draw_rectangle) \
		(* GDK_DRAWABLE_CLASS(parent_class)->draw_rectangle)(___self,___gc,___filled,___x,___y,___width,___height); }
{
#define __GOB_FUNCTION__ "GGobi:Renderer::draw_rectangle"
{
#line 70 "renderer.gob"
	
    GDK_DRAWABLE_GET_CLASS(SELF(self)->_priv->buffer)->draw_rectangle(
      SELF(self)->_priv->buffer, gc, filled, x, y, width, height);
  }}
#line 523 "ggobi-renderer.c"
#undef __GOB_FUNCTION__
#undef PARENT_HANDLER

#line 74 "renderer.gob"
static void 
___5_ggobi_renderer_draw_arc (GdkDrawable * self G_GNUC_UNUSED, GdkGC * gc, gboolean filled, gint x, gint y, gint width, gint height, gint angle1, gint angle2)
#line 530 "ggobi-renderer.c"
#define PARENT_HANDLER(___self,___gc,___filled,___x,___y,___width,___height,___angle1,___angle2) \
	{ if(GDK_DRAWABLE_CLASS(parent_class)->draw_arc) \
		(* GDK_DRAWABLE_CLASS(parent_class)->draw_arc)(___self,___gc,___filled,___x,___y,___width,___height,___angle1,___angle2); }
{
#define __GOB_FUNCTION__ "GGobi:Renderer::draw_arc"
{
#line 77 "renderer.gob"
	
    GDK_DRAWABLE_GET_CLASS(SELF(self)->_priv->buffer)->draw_arc(
      SELF(self)->_priv->buffer, gc, filled, x, y, width, height, angle1, angle2);
  }}
#line 542 "ggobi-renderer.c"
#undef __GOB_FUNCTION__
#undef PARENT_HANDLER

#line 81 "renderer.gob"
static void 
___6_ggobi_renderer_draw_polygon (GdkDrawable * self G_GNUC_UNUSED, GdkGC * gc, gboolean filled, GdkPoint * points, gint npoints)
#line 549 "ggobi-renderer.c"
#define PARENT_HANDLER(___self,___gc,___filled,___points,___npoints) \
	{ if(GDK_DRAWABLE_CLASS(parent_class)->draw_polygon) \
		(* GDK_DRAWABLE_CLASS(parent_class)->draw_polygon)(___self,___gc,___filled,___points,___npoints); }
{
#define __GOB_FUNCTION__ "GGobi:Renderer::draw_polygon"
{
#line 84 "renderer.gob"
	
    GDK_DRAWABLE_GET_CLASS(SELF(self)->_priv->buffer)->draw_polygon(
      SELF(self)->_priv->buffer, gc, filled, points, npoints);
  }}
#line 561 "ggobi-renderer.c"
#undef __GOB_FUNCTION__
#undef PARENT_HANDLER

#line 88 "renderer.gob"
static void 
___7_ggobi_renderer_draw_points (GdkDrawable * self G_GNUC_UNUSED, GdkGC * gc, GdkPoint * points, gint npoints)
#line 568 "ggobi-renderer.c"
#define PARENT_HANDLER(___self,___gc,___points,___npoints) \
	{ if(GDK_DRAWABLE_CLASS(parent_class)->draw_points) \
		(* GDK_DRAWABLE_CLASS(parent_class)->draw_points)(___self,___gc,___points,___npoints); }
{
#define __GOB_FUNCTION__ "GGobi:Renderer::draw_points"
{
#line 90 "renderer.gob"
	
    GDK_DRAWABLE_GET_CLASS(SELF(self)->_priv->buffer)->draw_points(
      SELF(self)->_priv->buffer, gc, points, npoints);
  }}
#line 580 "ggobi-renderer.c"
#undef __GOB_FUNCTION__
#undef PARENT_HANDLER

#line 94 "renderer.gob"
static void 
___8_ggobi_renderer_draw_segments (GdkDrawable * self G_GNUC_UNUSED, GdkGC * gc, GdkSegment * segs, gint nsegs)
#line 587 "ggobi-renderer.c"
#define PARENT_HANDLER(___self,___gc,___segs,___nsegs) \
	{ if(GDK_DRAWABLE_CLASS(parent_class)->draw_segments) \
		(* GDK_DRAWABLE_CLASS(parent_class)->draw_segments)(___self,___gc,___segs,___nsegs); }
{
#define __GOB_FUNCTION__ "GGobi:Renderer::draw_segments"
{
#line 96 "renderer.gob"
	
    GDK_DRAWABLE_GET_CLASS(SELF(self)->_priv->buffer)->draw_segments(
      SELF(self)->_priv->buffer, gc, segs, nsegs);
  }}
#line 599 "ggobi-renderer.c"
#undef __GOB_FUNCTION__
#undef PARENT_HANDLER

#line 100 "renderer.gob"
static void 
___9_ggobi_renderer_draw_lines (GdkDrawable * self G_GNUC_UNUSED, GdkGC * gc, GdkPoint * points, gint npoints)
#line 606 "ggobi-renderer.c"
#define PARENT_HANDLER(___self,___gc,___points,___npoints) \
	{ if(GDK_DRAWABLE_CLASS(parent_class)->draw_lines) \
		(* GDK_DRAWABLE_CLASS(parent_class)->draw_lines)(___self,___gc,___points,___npoints); }
{
#define __GOB_FUNCTION__ "GGobi:Renderer::draw_lines"
{
#line 102 "renderer.gob"
	
    GDK_DRAWABLE_GET_CLASS(SELF(self)->_priv->buffer)->draw_lines(
      SELF(self)->_priv->buffer, gc, points, npoints);
  }}
#line 618 "ggobi-renderer.c"
#undef __GOB_FUNCTION__
#undef PARENT_HANDLER

#line 106 "renderer.gob"
static void 
___a_ggobi_renderer_draw_trapezoids (GdkDrawable * self G_GNUC_UNUSED, GdkGC * gc, GdkTrapezoid * trapezoids, gint n_trapezoids)
#line 625 "ggobi-renderer.c"
#define PARENT_HANDLER(___self,___gc,___trapezoids,___n_trapezoids) \
	{ if(GDK_DRAWABLE_CLASS(parent_class)->draw_trapezoids) \
		(* GDK_DRAWABLE_CLASS(parent_class)->draw_trapezoids)(___self,___gc,___trapezoids,___n_trapezoids); }
{
#define __GOB_FUNCTION__ "GGobi:Renderer::draw_trapezoids"
{
#line 109 "renderer.gob"
	
    GDK_DRAWABLE_GET_CLASS(SELF(self)->_priv->buffer)->draw_trapezoids(
      SELF(self)->_priv->buffer, gc, trapezoids, n_trapezoids);
  }}
#line 637 "ggobi-renderer.c"
#undef __GOB_FUNCTION__
#undef PARENT_HANDLER

#line 114 "renderer.gob"
static void 
___b_ggobi_renderer_draw_text (GdkDrawable * self G_GNUC_UNUSED, GdkFont * font, GdkGC * gc, gint x, gint y, const gchar * text, gint text_length)
#line 644 "ggobi-renderer.c"
#define PARENT_HANDLER(___self,___font,___gc,___x,___y,___text,___text_length) \
	{ if(GDK_DRAWABLE_CLASS(parent_class)->draw_text) \
		(* GDK_DRAWABLE_CLASS(parent_class)->draw_text)(___self,___font,___gc,___x,___y,___text,___text_length); }
{
#define __GOB_FUNCTION__ "GGobi:Renderer::draw_text"
{
#line 117 "renderer.gob"
	
    GDK_DRAWABLE_GET_CLASS(SELF(self)->_priv->buffer)->draw_text(
      SELF(self)->_priv->buffer, font, gc, x, y, text, text_length);
  }}
#line 656 "ggobi-renderer.c"
#undef __GOB_FUNCTION__
#undef PARENT_HANDLER

#line 121 "renderer.gob"
static void 
___c_ggobi_renderer_draw_text_wc (GdkDrawable * self G_GNUC_UNUSED, GdkFont * font, GdkGC * gc, gint x, gint y, const GdkWChar * text, gint text_length)
#line 663 "ggobi-renderer.c"
#define PARENT_HANDLER(___self,___font,___gc,___x,___y,___text,___text_length) \
	{ if(GDK_DRAWABLE_CLASS(parent_class)->draw_text_wc) \
		(* GDK_DRAWABLE_CLASS(parent_class)->draw_text_wc)(___self,___font,___gc,___x,___y,___text,___text_length); }
{
#define __GOB_FUNCTION__ "GGobi:Renderer::draw_text_wc"
{
#line 124 "renderer.gob"
	
    GDK_DRAWABLE_GET_CLASS(SELF(self)->_priv->buffer)->draw_text_wc(
      SELF(self)->_priv->buffer, font, gc, x, y, text, text_length);
  }}
#line 675 "ggobi-renderer.c"
#undef __GOB_FUNCTION__
#undef PARENT_HANDLER

#line 128 "renderer.gob"
static void 
___d_ggobi_renderer_draw_glyphs (GdkDrawable * self G_GNUC_UNUSED, GdkGC * gc, PangoFont * font, gint x, gint y, PangoGlyphString * glyphs)
#line 682 "ggobi-renderer.c"
#define PARENT_HANDLER(___self,___gc,___font,___x,___y,___glyphs) \
	{ if(GDK_DRAWABLE_CLASS(parent_class)->draw_glyphs) \
		(* GDK_DRAWABLE_CLASS(parent_class)->draw_glyphs)(___self,___gc,___font,___x,___y,___glyphs); }
{
#define __GOB_FUNCTION__ "GGobi:Renderer::draw_glyphs"
{
#line 131 "renderer.gob"
	
    GDK_DRAWABLE_GET_CLASS(SELF(self)->_priv->buffer)->draw_glyphs(
      SELF(self)->_priv->buffer, gc, font, x, y, glyphs);
  }}
#line 694 "ggobi-renderer.c"
#undef __GOB_FUNCTION__
#undef PARENT_HANDLER

#line 135 "renderer.gob"
static void 
___e_ggobi_renderer_draw_glyphs_transformed (GdkDrawable * self G_GNUC_UNUSED, GdkGC * gc, PangoMatrix * matrix, PangoFont * font, gint x, gint y, PangoGlyphString * glyphs)
#line 701 "ggobi-renderer.c"
#define PARENT_HANDLER(___self,___gc,___matrix,___font,___x,___y,___glyphs) \
	{ if(GDK_DRAWABLE_CLASS(parent_class)->draw_glyphs_transformed) \
		(* GDK_DRAWABLE_CLASS(parent_class)->draw_glyphs_transformed)(___self,___gc,___matrix,___font,___x,___y,___glyphs); }
{
#define __GOB_FUNCTION__ "GGobi:Renderer::draw_glyphs_transformed"
{
#line 138 "renderer.gob"
	
    GDK_DRAWABLE_GET_CLASS(SELF(self)->_priv->buffer)->draw_glyphs_transformed(
      SELF(self)->_priv->buffer, gc, matrix, font, x, y, glyphs);
  }}
#line 713 "ggobi-renderer.c"
#undef __GOB_FUNCTION__
#undef PARENT_HANDLER

#line 143 "renderer.gob"
static GdkGC * 
___f_ggobi_renderer_create_gc (GdkDrawable * self G_GNUC_UNUSED, GdkGCValues * values, GdkGCValuesMask mask)
#line 720 "ggobi-renderer.c"
#define PARENT_HANDLER(___self,___values,___mask) \
	((GDK_DRAWABLE_CLASS(parent_class)->create_gc)? \
		(* GDK_DRAWABLE_CLASS(parent_class)->create_gc)(___self,___values,___mask): \
		((GdkGC * )0))
{
#define __GOB_FUNCTION__ "GGobi:Renderer::create_gc"
{
#line 145 "renderer.gob"
	
    return GDK_DRAWABLE_GET_CLASS(SELF(self)->_priv->buffer)->create_gc(
      SELF(self)->_priv->buffer, values, mask);
  }}
#line 733 "ggobi-renderer.c"
#undef __GOB_FUNCTION__
#undef PARENT_HANDLER

#line 149 "renderer.gob"
static void 
___10_ggobi_renderer_draw_drawable (GdkDrawable * self G_GNUC_UNUSED, GdkGC * gc, GdkDrawable * src, gint xsrc, gint ysrc, gint xdest, gint ydest, gint width, gint height)
#line 740 "ggobi-renderer.c"
#define PARENT_HANDLER(___self,___gc,___src,___xsrc,___ysrc,___xdest,___ydest,___width,___height) \
	{ if(GDK_DRAWABLE_CLASS(parent_class)->draw_drawable) \
		(* GDK_DRAWABLE_CLASS(parent_class)->draw_drawable)(___self,___gc,___src,___xsrc,___ysrc,___xdest,___ydest,___width,___height); }
{
#define __GOB_FUNCTION__ "GGobi:Renderer::draw_drawable"
{
#line 152 "renderer.gob"
	
    GDK_DRAWABLE_GET_CLASS(SELF(self)->_priv->buffer)->draw_drawable(
      SELF(self)->_priv->buffer, gc, src, xsrc, ysrc, xdest, ydest, width, height);
  }}
#line 752 "ggobi-renderer.c"
#undef __GOB_FUNCTION__
#undef PARENT_HANDLER

#line 156 "renderer.gob"
static void 
___11_ggobi_renderer_draw_image (GdkDrawable * self G_GNUC_UNUSED, GdkGC * gc, GdkImage * image, gint xsrc, gint ysrc, gint xdest, gint ydest, gint width, gint height)
#line 759 "ggobi-renderer.c"
#define PARENT_HANDLER(___self,___gc,___image,___xsrc,___ysrc,___xdest,___ydest,___width,___height) \
	{ if(GDK_DRAWABLE_CLASS(parent_class)->draw_image) \
		(* GDK_DRAWABLE_CLASS(parent_class)->draw_image)(___self,___gc,___image,___xsrc,___ysrc,___xdest,___ydest,___width,___height); }
{
#define __GOB_FUNCTION__ "GGobi:Renderer::draw_image"
{
#line 159 "renderer.gob"
	
    GDK_DRAWABLE_GET_CLASS(SELF(self)->_priv->buffer)->draw_image(
      SELF(self)->_priv->buffer, gc, image, xsrc, ysrc, xdest, ydest, width, height);
  }}
#line 771 "ggobi-renderer.c"
#undef __GOB_FUNCTION__
#undef PARENT_HANDLER

#line 164 "renderer.gob"
static gint 
___12_ggobi_renderer_get_depth (GdkDrawable * self G_GNUC_UNUSED)
#line 778 "ggobi-renderer.c"
#define PARENT_HANDLER(___self) \
	((GDK_DRAWABLE_CLASS(parent_class)->get_depth)? \
		(* GDK_DRAWABLE_CLASS(parent_class)->get_depth)(___self): \
		((gint )0))
{
#define __GOB_FUNCTION__ "GGobi:Renderer::get_depth"
{
#line 166 "renderer.gob"
	
    return GDK_DRAWABLE_GET_CLASS(SELF(self)->_priv->buffer)->get_depth(
      SELF(self)->_priv->buffer);
  }}
#line 791 "ggobi-renderer.c"
#undef __GOB_FUNCTION__
#undef PARENT_HANDLER

#line 170 "renderer.gob"
static void 
___13_ggobi_renderer_get_size (GdkDrawable * self G_GNUC_UNUSED, gint * width, gint * height)
#line 798 "ggobi-renderer.c"
#define PARENT_HANDLER(___self,___width,___height) \
	{ if(GDK_DRAWABLE_CLASS(parent_class)->get_size) \
		(* GDK_DRAWABLE_CLASS(parent_class)->get_size)(___self,___width,___height); }
{
#define __GOB_FUNCTION__ "GGobi:Renderer::get_size"
{
#line 172 "renderer.gob"
	
    GDK_DRAWABLE_GET_CLASS(SELF(self)->_priv->buffer)->get_size(
      SELF(self)->_priv->buffer, width, height);
  }}
#line 810 "ggobi-renderer.c"
#undef __GOB_FUNCTION__
#undef PARENT_HANDLER

#line 177 "renderer.gob"
static void 
___14_ggobi_renderer_set_colormap (GdkDrawable * self G_GNUC_UNUSED, GdkColormap * cmap)
#line 817 "ggobi-renderer.c"
#define PARENT_HANDLER(___self,___cmap) \
	{ if(GDK_DRAWABLE_CLASS(parent_class)->set_colormap) \
		(* GDK_DRAWABLE_CLASS(parent_class)->set_colormap)(___self,___cmap); }
{
#define __GOB_FUNCTION__ "GGobi:Renderer::set_colormap"
{
#line 179 "renderer.gob"
	
    GDK_DRAWABLE_GET_CLASS(SELF(self)->_priv->buffer)->set_colormap(
      SELF(self)->_priv->buffer, cmap);
  }}
#line 829 "ggobi-renderer.c"
#undef __GOB_FUNCTION__
#undef PARENT_HANDLER

#line 183 "renderer.gob"
static GdkColormap * 
___15_ggobi_renderer_get_colormap (GdkDrawable * self G_GNUC_UNUSED)
#line 836 "ggobi-renderer.c"
#define PARENT_HANDLER(___self) \
	((GDK_DRAWABLE_CLASS(parent_class)->get_colormap)? \
		(* GDK_DRAWABLE_CLASS(parent_class)->get_colormap)(___self): \
		((GdkColormap * )0))
{
#define __GOB_FUNCTION__ "GGobi:Renderer::get_colormap"
{
#line 185 "renderer.gob"
	
    return GDK_DRAWABLE_GET_CLASS(SELF(self)->_priv->buffer)->get_colormap(
      SELF(self)->_priv->buffer);
  }}
#line 849 "ggobi-renderer.c"
#undef __GOB_FUNCTION__
#undef PARENT_HANDLER

#line 189 "renderer.gob"
static GdkVisual * 
___16_ggobi_renderer_get_visual (GdkDrawable * self G_GNUC_UNUSED)
#line 856 "ggobi-renderer.c"
#define PARENT_HANDLER(___self) \
	((GDK_DRAWABLE_CLASS(parent_class)->get_visual)? \
		(* GDK_DRAWABLE_CLASS(parent_class)->get_visual)(___self): \
		((GdkVisual * )0))
{
#define __GOB_FUNCTION__ "GGobi:Renderer::get_visual"
{
#line 191 "renderer.gob"
	
    return GDK_DRAWABLE_GET_CLASS(SELF(self)->_priv->buffer)->get_visual(
      SELF(self)->_priv->buffer);
  }}
#line 869 "ggobi-renderer.c"
#undef __GOB_FUNCTION__
#undef PARENT_HANDLER

#line 195 "renderer.gob"
static GdkScreen * 
___17_ggobi_renderer_get_screen (GdkDrawable * self G_GNUC_UNUSED)
#line 876 "ggobi-renderer.c"
#define PARENT_HANDLER(___self) \
	((GDK_DRAWABLE_CLASS(parent_class)->get_screen)? \
		(* GDK_DRAWABLE_CLASS(parent_class)->get_screen)(___self): \
		((GdkScreen * )0))
{
#define __GOB_FUNCTION__ "GGobi:Renderer::get_screen"
{
#line 197 "renderer.gob"
	
    return GDK_DRAWABLE_GET_CLASS(SELF(self)->_priv->buffer)->get_screen(
      SELF(self)->_priv->buffer);
  }}
#line 889 "ggobi-renderer.c"
#undef __GOB_FUNCTION__
#undef PARENT_HANDLER

#line 201 "renderer.gob"
static GdkImage * 
___18_ggobi_renderer_get_image (GdkDrawable * self G_GNUC_UNUSED, gint x, gint y, gint width, gint height)
#line 896 "ggobi-renderer.c"
#define PARENT_HANDLER(___self,___x,___y,___width,___height) \
	((GDK_DRAWABLE_CLASS(parent_class)->get_image)? \
		(* GDK_DRAWABLE_CLASS(parent_class)->get_image)(___self,___x,___y,___width,___height): \
		((GdkImage * )0))
{
#define __GOB_FUNCTION__ "GGobi:Renderer::get_image"
{
#line 203 "renderer.gob"
	
    return GDK_DRAWABLE_GET_CLASS(SELF(self)->_priv->buffer)->get_image(
      SELF(self)->_priv->buffer, x, y, width, height);
  }}
#line 909 "ggobi-renderer.c"
#undef __GOB_FUNCTION__
#undef PARENT_HANDLER

#line 207 "renderer.gob"
static GdkRegion * 
___19_ggobi_renderer_get_clip_region (GdkDrawable * self G_GNUC_UNUSED)
#line 916 "ggobi-renderer.c"
#define PARENT_HANDLER(___self) \
	((GDK_DRAWABLE_CLASS(parent_class)->get_clip_region)? \
		(* GDK_DRAWABLE_CLASS(parent_class)->get_clip_region)(___self): \
		((GdkRegion * )0))
{
#define __GOB_FUNCTION__ "GGobi:Renderer::get_clip_region"
{
#line 209 "renderer.gob"
	
    return GDK_DRAWABLE_GET_CLASS(SELF(self)->_priv->buffer)->get_clip_region(
      SELF(self)->_priv->buffer);
  }}
#line 929 "ggobi-renderer.c"
#undef __GOB_FUNCTION__
#undef PARENT_HANDLER

#line 213 "renderer.gob"
static GdkRegion * 
___1a_ggobi_renderer_get_visible_region (GdkDrawable * self G_GNUC_UNUSED)
#line 936 "ggobi-renderer.c"
#define PARENT_HANDLER(___self) \
	((GDK_DRAWABLE_CLASS(parent_class)->get_visible_region)? \
		(* GDK_DRAWABLE_CLASS(parent_class)->get_visible_region)(___self): \
		((GdkRegion * )0))
{
#define __GOB_FUNCTION__ "GGobi:Renderer::get_visible_region"
{
#line 215 "renderer.gob"
	
    return GDK_DRAWABLE_GET_CLASS(SELF(self)->_priv->buffer)->get_visible_region(
      SELF(self)->_priv->buffer);
  }}
#line 949 "ggobi-renderer.c"
#undef __GOB_FUNCTION__
#undef PARENT_HANDLER

#line 219 "renderer.gob"
static GdkDrawable * 
___1b_ggobi_renderer_get_composite_drawable (GdkDrawable * self G_GNUC_UNUSED, gint x, gint y, gint width, gint height, gint * composite_x_offset, gint * composite_y_offset)
#line 956 "ggobi-renderer.c"
#define PARENT_HANDLER(___self,___x,___y,___width,___height,___composite_x_offset,___composite_y_offset) \
	((GDK_DRAWABLE_CLASS(parent_class)->get_composite_drawable)? \
		(* GDK_DRAWABLE_CLASS(parent_class)->get_composite_drawable)(___self,___x,___y,___width,___height,___composite_x_offset,___composite_y_offset): \
		((GdkDrawable * )0))
{
#define __GOB_FUNCTION__ "GGobi:Renderer::get_composite_drawable"
{
#line 222 "renderer.gob"
	
    return GDK_DRAWABLE_GET_CLASS(SELF(self)->_priv->buffer)->get_composite_drawable(
      SELF(self)->_priv->buffer, x, y, width, height, composite_x_offset, composite_y_offset);
  }}
#line 969 "ggobi-renderer.c"
#undef __GOB_FUNCTION__
#undef PARENT_HANDLER

#line 227 "renderer.gob"
static void 
___1c_ggobi_renderer_draw_pixbuf (GdkDrawable * self G_GNUC_UNUSED, GdkGC * gc, GdkPixbuf * pixbuf, gint src_x, gint src_y, gint dest_x, gint dest_y, gint width, gint height, GdkRgbDither dither, gint x_dither, gint y_dither)
#line 976 "ggobi-renderer.c"
#define PARENT_HANDLER(___self,___gc,___pixbuf,___src_x,___src_y,___dest_x,___dest_y,___width,___height,___dither,___x_dither,___y_dither) \
	{ if(GDK_DRAWABLE_CLASS(parent_class)->draw_pixbuf) \
		(* GDK_DRAWABLE_CLASS(parent_class)->draw_pixbuf)(___self,___gc,___pixbuf,___src_x,___src_y,___dest_x,___dest_y,___width,___height,___dither,___x_dither,___y_dither); }
{
#define __GOB_FUNCTION__ "GGobi:Renderer::draw_pixbuf"
{
#line 231 "renderer.gob"
	
    GDK_DRAWABLE_GET_CLASS(SELF(self)->_priv->buffer)->draw_pixbuf(
      SELF(self)->_priv->buffer, gc, pixbuf, src_x, src_y, dest_x, dest_y, 
      width, height, dither, x_dither, y_dither);
  }}
#line 989 "ggobi-renderer.c"
#undef __GOB_FUNCTION__
#undef PARENT_HANDLER

#line 236 "renderer.gob"
static GdkImage * 
___1d_ggobi_renderer__copy_to_image (GdkDrawable * self G_GNUC_UNUSED, GdkImage * image, gint src_x, gint src_y, gint dest_x, gint dest_y, gint width, gint height)
#line 996 "ggobi-renderer.c"
#define PARENT_HANDLER(___self,___image,___src_x,___src_y,___dest_x,___dest_y,___width,___height) \
	((GDK_DRAWABLE_CLASS(parent_class)->_copy_to_image)? \
		(* GDK_DRAWABLE_CLASS(parent_class)->_copy_to_image)(___self,___image,___src_x,___src_y,___dest_x,___dest_y,___width,___height): \
		((GdkImage * )0))
{
#define __GOB_FUNCTION__ "GGobi:Renderer::_copy_to_image"
{
#line 239 "renderer.gob"
	
    return GDK_DRAWABLE_GET_CLASS(SELF(self)->_priv->buffer)->_copy_to_image(
      SELF(self)->_priv->buffer, image, src_x, src_y, dest_x, dest_y, width, height);
  }}
#line 1009 "ggobi-renderer.c"
#undef __GOB_FUNCTION__
#undef PARENT_HANDLER


#line 251 "renderer.gob"

  #if GTK_CHECK_VERSION(2,8,0)
  static cairo_surface_t *
  ref_cairo_surface(GdkDrawable *self)
  {
    return GDK_DRAWABLE_GET_CLASS(GGOBI_RENDERER(self)->_priv->buffer)->ref_cairo_surface(
      GGOBI_RENDERER(self)->_priv->buffer);
  }
  #endif

#line 1025 "ggobi-renderer.c"
